#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
hermes-usage  单文件安装器 (Token 用量: Hermes 底部实时用量条 + /usage 历史详情页)

在一台已安装 Hermes 的机器上运行即可直接使用:

    方式A(完整版,含历史详情页,推荐):    python install_hermes_usage.py
    方式B(仅底部用量条,免改配置,零依赖): python install_hermes_usage.py --bar-only

自动探测 Hermes 数据目录(HERMES_HOME)并按需写入:
    <home>/desktop-plugins/hermes-usage/plugin.js
    <home>/plugins/hermes-usage/dashboard/{manifest.json,plugin_api.py}
并把插件加入 config.yaml 的 plugins.enabled(会先备份 config.yaml.bak-hermes-usage)。

安装后: 彻底退出 Hermes 桌面端(含托盘)再打开; 若底部条没出现,
按 Ctrl+K 输入 Reload desktop plugins 回车。数据来自 Hermes 自带的
state.db(session_model_usage), 不拦截、不改库。
"""
import base64
import os
import sys
from pathlib import Path

__version__ = "0.3.1"

B64_desktop_plugins_hermes_usage_plugin_js = (
        "LyoqCiAqIGhlcm1lcy11c2FnZSDigJQgdG9rZW4tdXNhZ2UgYmFyIGRvY2tlZCBhdCB0aGUgQk9U"
        "VE9NIG9mIHRoZSBIZXJtZXMgVUkuCiAqCiAqIEJvdHRvbSBwYW5lIChhbHdheXMgdmlzaWJsZSwg"
        "bGlrZSBhIERlZXBTZWVrLUhhcm5lc3MgYm90dG9tIGJhcikgc2hvd2luZyB0aGUKICogRk9DVVNF"
        "RCBzZXNzaW9uJ3MgbGl2ZSB1c2FnZSwgc3RyZWFtZWQgdmlhIGhvc3Quc3RhdGUuZm9jdXNlZFVz"
        "YWdlIChubwogKiBiYWNrZW5kIG5lZWRlZCk6IGlucHV0IC8gb3V0cHV0IC8gY2FjaGUtaGl0JSAv"
        "IHRvdGFsIC8gY2FsbHMgLyBjb3N0LgogKiBDbGljayB0aGUgYmFyIHRvIG9wZW4gdGhlIGZ1bGwg"
        "L3VzYWdlIGRldGFpbCBwYWdlIChyZWFkcyBzdGF0ZS5kYiB2aWEgdGhlCiAqIHNpYmxpbmcgcGx1"
        "Z2luX2FwaS5weSBiYWNrZW5kIGZvciBwZXItbW9kZWwgJiBwZXItc2Vzc2lvbiBoaXN0b3J5KS4K"
        "ICoKICogUGxhaW4gRVNNLCBsb2FkZWQgdW5jb21waWxlZCDigJQgVUkgaXMganN4KCkgY2FsbHMu"
        "IE9ubHkgdGhlc2UgaW1wb3J0cyByZXNvbHZlOgogKiAgIEBoZXJtZXMvcGx1Z2luLXNkaywgcmVh"
        "Y3QsIHJlYWN0L2pzeC1ydW50aW1lCiAqLwoKaW1wb3J0IHsgaG9zdCwgdXNlVmFsdWUsIGhhcHRp"
        "YywgUEFORVNfQVJFQSwgUk9VVEVTX0FSRUEsIFBBTEVUVEVfQVJFQSB9IGZyb20gJ0BoZXJtZXMv"
        "cGx1Z2luLXNkaycKaW1wb3J0IHsganN4LCBqc3hzIH0gZnJvbSAncmVhY3QvanN4LXJ1bnRpbWUn"
        "CmltcG9ydCB7IHVzZUVmZmVjdCwgdXNlU3RhdGUgfSBmcm9tICdyZWFjdCcKCmNvbnN0IElEID0g"
        "J2hlcm1lcy11c2FnZScKY29uc3QgUkVGUkVTSF9NUyA9IDIwMDAwCgovKiAtLS0tLS0tLS0tIG51"
        "bWJlciBmb3JtYXR0aW5nIC0tLS0tLS0tLS0gKi8KZnVuY3Rpb24gZm10KG4pIHsKICBpZiAobiA9"
        "PT0gbnVsbCB8fCBuID09PSB1bmRlZmluZWQgfHwgTnVtYmVyLmlzTmFOKE51bWJlcihuKSkpIHJl"
        "dHVybiAn4oCUJwogIG4gPSBOdW1iZXIobikKICBpZiAobiA8IDApIHJldHVybiAn4oCUJwogIGlm"
        "IChuID49IDFlOSkgcmV0dXJuIChuIC8gMWU5KS50b0ZpeGVkKDIpICsgJ0InCiAgaWYgKG4gPj0g"
        "MWU2KSByZXR1cm4gKG4gLyAxZTYpLnRvRml4ZWQoMikgKyAnTScKICBpZiAobiA+PSAxZTQpIHJl"
        "dHVybiAobiAvIDFlMykudG9GaXhlZCgxKSArICdLJwogIHJldHVybiBNYXRoLnJvdW5kKG4pLnRv"
        "TG9jYWxlU3RyaW5nKCkKfQpmdW5jdGlvbiBmbXRVc2QobikgewogIGlmIChuID09PSBudWxsIHx8"
        "IG4gPT09IHVuZGVmaW5lZCB8fCBuID09PSAwKSByZXR1cm4gJyQwJwogIGlmIChuIDwgMC4wMSkg"
        "cmV0dXJuICckJyArIG4udG9GaXhlZCg0KQogIHJldHVybiAnJCcgKyBuLnRvRml4ZWQoMikKfQpm"
        "dW5jdGlvbiBmbXREYXRlKHNlYykgewogIGlmICghc2VjKSByZXR1cm4gJ+KAlCcKICBjb25zdCBk"
        "ID0gbmV3IERhdGUoc2VjICogMTAwMCkKICBjb25zdCBwID0geCA9PiBTdHJpbmcoeCkucGFkU3Rh"
        "cnQoMiwgJzAnKQogIHJldHVybiBgJHtkLmdldEZ1bGxZZWFyKCl9LSR7cChkLmdldE1vbnRoKCkg"
        "KyAxKX0tJHtwKGQuZ2V0RGF0ZSgpKX0gJHtwKGQuZ2V0SG91cnMoKSl9OiR7cChkLmdldE1pbnV0"
        "ZXMoKSl9YAp9CgovKiAtLS0tLS0tLS0tIGxpdmUgYm90dG9tIGJhciAodGhlIGFsd2F5cy12aXNp"
        "YmxlIG1ldGVyKSAtLS0tLS0tLS0tICovCmZ1bmN0aW9uIE1ldGVyQ2hpcCh7IGxhYmVsLCB2YWx1"
        "ZSwgdGl0bGUsIHN0cm9uZyB9KSB7CiAgcmV0dXJuIGpzeHMoJ3NwYW4nLCB7CiAgICBjbGFzc05h"
        "bWU6ICdpbmxpbmUtZmxleCBpdGVtcy1iYXNlbGluZSBnYXAtMSB3aGl0ZXNwYWNlLW5vd3JhcCcs"
        "CiAgICB0aXRsZTogdGl0bGUsCiAgICBjaGlsZHJlbjogWwogICAgICBqc3goJ3NwYW4nLCB7IGNs"
        "YXNzTmFtZTogJ3RleHQtWzAuNjg3NXJlbV0gdGV4dC0oLS11aS10ZXh0LXF1YXRlcm5hcnkpJywg"
        "Y2hpbGRyZW46IGxhYmVsIH0pLAogICAgICBqc3goJ3NwYW4nLCB7CiAgICAgICAgY2xhc3NOYW1l"
        "OiBzdHJvbmcKICAgICAgICAgID8gJ3RleHQtWzAuODEyNXJlbV0gZm9udC1zZW1pYm9sZCB0YWJ1"
        "bGFyLW51bXMgdGV4dC0oLS11aS1hY2NlbnQpJwogICAgICAgICAgOiAndGV4dC1bMC42ODc1cmVt"
        "XSBmb250LW1lZGl1bSB0YWJ1bGFyLW51bXMgdGV4dC0oLS11aS10ZXh0LXNlY29uZGFyeSknLAog"
        "ICAgICAgIGNoaWxkcmVuOiB2YWx1ZQogICAgICB9KQogICAgXQogIH0pCn0KCmZ1bmN0aW9uIG1v"
        "ZGVsU2hvcnQobmFtZSkgewogIGlmICghbmFtZSkgcmV0dXJuICfigJQnCiAgY29uc3QgcyA9IFN0"
        "cmluZyhuYW1lKQogIGNvbnN0IGkgPSBzLmxhc3RJbmRleE9mKCcvJykKICByZXR1cm4gaSA+PSAw"
        "ID8gcy5zbGljZShpICsgMSkgOiBzCn0KCmZ1bmN0aW9uIEJvdHRvbUJhcih7IGxvYWRNb2RlbHMg"
        "fSkgewogIGNvbnN0IHUgPSB1c2VWYWx1ZShob3N0LnN0YXRlLmZvY3VzZWRVc2FnZSkKICBjb25z"
        "dCBtb2RlbCA9IHVzZVZhbHVlKGhvc3Quc3RhdGUubW9kZWwpCiAgY29uc3Qgc3RvcmVkSWQgPSB1"
        "c2VWYWx1ZShob3N0LnN0YXRlLmZvY3VzZWRTdG9yZWRTZXNzaW9uSWQpCiAgY29uc3QgW21vZGVs"
        "cywgc2V0TW9kZWxzXSA9IHVzZVN0YXRlKG51bGwpCiAgY29uc3QgW2xpdmUsIHNldExpdmVdID0g"
        "dXNlU3RhdGUobnVsbCkKICBjb25zdCBvcGVuID0gKCkgPT4geyBoYXB0aWMoJ3RhcCcpOyBob3N0"
        "Lm5hdmlnYXRlKCcvdXNhZ2UnKSB9CgogIC8vIExpdmUgb3V0cHV0IHJhdGU6IHN1YnNjcmliZSB0"
        "byBzdHJlYW1lZCB0ZXh0IGRlbHRhcyBhbmQgZGVyaXZlIHRvay9zIG92ZXIgYQogIC8vIH4ycyBz"
        "bGlkaW5nIHdpbmRvdyAoYXBwcm94aW1hdGUg4oCUIGRlcml2ZWQgZnJvbSBjaGFyYWN0ZXJzLCBu"
        "b3QgYmlsbGluZykuCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGNvbnN0IHdpbiA9IFtdCiAgICBj"
        "b25zdCBLID0gMy41CiAgICBsZXQgbGFzdEV2ZW50ID0gMAogICAgY29uc3QgcHVzaCA9IGNoYXJz"
        "ID0+IHsgY29uc3Qgbm93ID0gRGF0ZS5ub3coKTsgd2luLnB1c2goW25vdywgY2hhcnNdKTsgbGFz"
        "dEV2ZW50ID0gbm93IH0KICAgIGNvbnN0IG9uRXYgPSBldiA9PiB7CiAgICAgIGlmICghZXYgfHwg"
        "IWV2LnR5cGUpIHJldHVybgogICAgICBjb25zdCB0ID0gZXYudHlwZQogICAgICBpZiAodCAhPT0g"
        "J21lc3NhZ2UuZGVsdGEnICYmIHQgIT09ICdyZWFzb25pbmcuZGVsdGEnICYmIHQgIT09ICd0aGlu"
        "a2luZy5kZWx0YScpIHJldHVybgogICAgICBjb25zdCBmSWQgPSBob3N0LnN0YXRlLmZvY3VzZWRT"
        "ZXNzaW9uSWQuZ2V0KCkKICAgICAgaWYgKGV2LnNlc3Npb25faWQgJiYgZklkICYmIGV2LnNlc3Np"
        "b25faWQgIT09IGZJZCkgcmV0dXJuCiAgICAgIGNvbnN0IHRleHQgPSBldi5wYXlsb2FkICYmIHR5"
        "cGVvZiBldi5wYXlsb2FkLnRleHQgPT09ICdzdHJpbmcnID8gZXYucGF5bG9hZC50ZXh0IDogJycK"
        "ICAgICAgaWYgKHRleHQpIHB1c2godGV4dC5sZW5ndGgpCiAgICB9CiAgICBsZXQgZGlzcG9zZSA9"
        "IG51bGwKICAgIHRyeSB7IGRpc3Bvc2UgPSBob3N0Lm9uRXZlbnQoJyonLCBvbkV2KSB9IGNhdGNo"
        "IChlKSB7IGRpc3Bvc2UgPSBudWxsIH0KICAgIGNvbnN0IGlkID0gc2V0SW50ZXJ2YWwoKCkgPT4g"
        "ewogICAgICBjb25zdCBub3cgPSBEYXRlLm5vdygpCiAgICAgIHdoaWxlICh3aW4ubGVuZ3RoICYm"
        "IG5vdyAtIHdpblswXVswXSA+IDIwMDApIHdpbi5zaGlmdCgpCiAgICAgIGNvbnN0IGNoYXJzID0g"
        "d2luLnJlZHVjZSgoYSwgeCkgPT4gYSArIHhbMV0sIDApCiAgICAgIGNvbnN0IHNwYW4gPSB3aW4u"
        "bGVuZ3RoID8gTWF0aC5tYXgoKG5vdyAtIHdpblswXVswXSkgLyAxMDAwLCAwLjUpIDogMAogICAg"
        "ICBjb25zdCBzdHJlYW1pbmcgPSB3aW4ubGVuZ3RoID4gMCAmJiAobm93IC0gbGFzdEV2ZW50KSA8"
        "IDE1MDAKICAgICAgc2V0TGl2ZShzdHJlYW1pbmcgPyB7IHRwczogKGNoYXJzIC8gc3BhbikgLyBL"
        "IH0gOiBudWxsKQogICAgfSwgNTAwKQogICAgcmV0dXJuICgpID0+IHsgY2xlYXJJbnRlcnZhbChp"
        "ZCk7IGlmICh0eXBlb2YgZGlzcG9zZSA9PT0gJ2Z1bmN0aW9uJykgZGlzcG9zZSgpIH0KICB9LCBb"
        "XSkKCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGxldCBhbGl2ZSA9IHRydWUKICAgIGlmICghc3Rv"
        "cmVkSWQgfHwgIWxvYWRNb2RlbHMpIHsgc2V0TW9kZWxzKG51bGwpOyByZXR1cm4gKCkgPT4geyBh"
        "bGl2ZSA9IGZhbHNlIH0gfQogICAgY29uc3QgcnVuID0gKCkgPT4gewogICAgICBsb2FkTW9kZWxz"
        "KHN0b3JlZElkKS50aGVuKHJlcyA9PiB7CiAgICAgICAgaWYgKCFhbGl2ZSkgcmV0dXJuCiAgICAg"
        "ICAgc2V0TW9kZWxzKHJlcyAmJiByZXMub2sgJiYgQXJyYXkuaXNBcnJheShyZXMubW9kZWxzKSA/"
        "IHJlcy5tb2RlbHMgOiBudWxsKQogICAgICB9KS5jYXRjaCgoKSA9PiB7IGlmIChhbGl2ZSkgc2V0"
        "TW9kZWxzKG51bGwpIH0pCiAgICB9CiAgICBydW4oKQogICAgY29uc3QgaWQgPSBzZXRJbnRlcnZh"
        "bChydW4sIFJFRlJFU0hfTVMpCiAgICByZXR1cm4gKCkgPT4geyBhbGl2ZSA9IGZhbHNlOyBjbGVh"
        "ckludGVydmFsKGlkKSB9CiAgfSwgW3N0b3JlZElkLCBsb2FkTW9kZWxzXSkKCiAgY29uc3QgbXVs"
        "dGkgPSBtb2RlbHMgJiYgbW9kZWxzLmxlbmd0aCA+IDEKCiAgcmV0dXJuIGpzeHMoJ2J1dHRvbics"
        "IHsKICAgIHR5cGU6ICdidXR0b24nLAogICAgb25DbGljazogb3BlbiwKICAgIHRpdGxlOiAn54K5"
        "5Ye75omT5byAIFRva2VuIOeUqOmHj+ivpuaDhemhtScsCiAgICBjbGFzc05hbWU6ICdmbGV4IGgt"
        "ZnVsbCB3LWZ1bGwgZmxleC1jb2wganVzdGlmeS1jZW50ZXIgZ2FwLTAuNSBvdmVyZmxvdy1oaWRk"
        "ZW4gcHgtMiB0ZXh0LWxlZnQgdGV4dC0oLS11aS10ZXh0LXNlY29uZGFyeSkgaG92ZXI6dGV4dC1m"
        "b3JlZ3JvdW5kJywKICAgIGNoaWxkcmVuOiBbCiAgICAgICF1ICYmICFtb2RlbAogICAgICAgID8g"
        "anN4KCdzcGFuJywgeyBjbGFzc05hbWU6ICd0ZXh0LVswLjY4NzVyZW1dIHRleHQtKC0tdWktdGV4"
        "dC10ZXJ0aWFyeSknLCBjaGlsZHJlbjogJ1Rva2VuIOeUqOmHjyDigJQg5pqC5peg5rS75Yqo5Lya"
        "6K+dJyB9KQogICAgICAgIDoganN4cygnZGl2JywgewogICAgICAgICAgICBjbGFzc05hbWU6ICdm"
        "bGV4IGl0ZW1zLWNlbnRlciBnYXAtMyBvdmVyZmxvdy1oaWRkZW4nLAogICAgICAgICAgICBjaGls"
        "ZHJlbjogWwogICAgICAgICAgICAgIGpzeCgnc3BhbicsIHsKICAgICAgICAgICAgICAgIGNsYXNz"
        "TmFtZTogJ2lubGluZS1mbGV4IG1heC13LVsyMTBweF0gaXRlbXMtY2VudGVyIGdhcC0xIHRydW5j"
        "YXRlIHdoaXRlc3BhY2Utbm93cmFwIHRleHQtWzAuNjg3NXJlbV0gZm9udC1zZW1pYm9sZCB0ZXh0"
        "LSgtLXVpLWFjY2VudCknLAogICAgICAgICAgICAgICAgdGl0bGU6ICflvZPliY3mqKHlnos6ICcg"
        "KyAobW9kZWwgfHwgJ+KAlCcpLAogICAgICAgICAgICAgICAgY2hpbGRyZW46IG1vZGVsID8gJ+ao"
        "oeWeiyAnICsgbW9kZWxTaG9ydChtb2RlbCkgOiAn5qih5Z6LIOKAlCcKICAgICAgICAgICAgICB9"
        "KSwKICAgICAgICAgICAgICBsaXZlCiAgICAgICAgICAgICAgICA/IGpzeCgnc3BhbicsIHsKICAg"
        "ICAgICAgICAgICAgICAgICBjbGFzc05hbWU6ICdpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIgZ2Fw"
        "LTEgd2hpdGVzcGFjZS1ub3dyYXAgcm91bmRlZCBiZy0oLS11aS1iZy1lbGV2YXRlZCkgcHgtMS41"
        "IHB5LXB4IHRleHQtWzAuNjg3NXJlbV0gZm9udC1zZW1pYm9sZCB0ZXh0LSgtLXVpLWFjY2VudCkn"
        "LAogICAgICAgICAgICAgICAgICAgIHRpdGxlOiAn5a6e5pe26L6T5Ye66YCf546H77yI5oyJ5rWB"
        "5byP5a2X56ym5Lyw566X77yM6Z2e57K+56Gu6K6h6LS55Y+j5b6E77yJJywKICAgICAgICAgICAg"
        "ICAgICAgICBjaGlsZHJlbjogJ+eUn+aIkOS4rSB+JyArIE1hdGgucm91bmQobGl2ZS50cHMpICsg"
        "JyB0b2svcycKICAgICAgICAgICAgICAgICAgfSkKICAgICAgICAgICAgICAgIDogbnVsbCwKICAg"
        "ICAgICAgICAgICB1ID8ganN4KE1ldGVyQ2hpcCwgeyBsYWJlbDogJ+i+k+WFpScsIHZhbHVlOiBm"
        "bXQodS5pbnB1dCksIHRpdGxlOiAn6L6T5YWlIHRva2VuJyB9KSA6IG51bGwsCiAgICAgICAgICAg"
        "ICAgdSA/IGpzeChNZXRlckNoaXAsIHsgbGFiZWw6ICfovpPlh7onLCB2YWx1ZTogZm10KHUub3V0"
        "cHV0KSwgdGl0bGU6ICfovpPlh7ogdG9rZW4nIH0pIDogbnVsbCwKICAgICAgICAgICAgICB1ICYm"
        "IHUuY2FjaGVfaGl0X3BjdCAhPSBudWxsCiAgICAgICAgICAgICAgICA/IGpzeChNZXRlckNoaXAs"
        "IHsgbGFiZWw6ICfnvJPlrZjlkb3kuK0nLCB2YWx1ZTogdS5jYWNoZV9oaXRfcGN0ICsgJyUnLCB0"
        "aXRsZTogJ+W9k+WJjeS8muivneaPkOekuuivjee8k+WtmOWRveS4reeOhycgfSkKICAgICAgICAg"
        "ICAgICAgIDogbnVsbCwKICAgICAgICAgICAgICB1ID8ganN4KE1ldGVyQ2hpcCwgeyBsYWJlbDog"
        "J+aAuycsIHZhbHVlOiBmbXQodS50b3RhbCksIHRpdGxlOiAn5oC7IHRva2Vu77yI5ZCr57yT5a2Y"
        "77yJJywgc3Ryb25nOiB0cnVlIH0pIDogbnVsbCwKICAgICAgICAgICAgICB1ID8ganN4KE1ldGVy"
        "Q2hpcCwgeyBsYWJlbDogJ+iwg+eUqCcsIHZhbHVlOiB1LmNhbGxzID8/IDAsIHRpdGxlOiAnQVBJ"
        "IOiwg+eUqOasoeaVsCcgfSkgOiBudWxsLAogICAgICAgICAgICAgIHUgJiYgdS5jb3N0X3VzZCAh"
        "PSBudWxsID8ganN4KE1ldGVyQ2hpcCwgeyBsYWJlbDogJ+i0ueeUqCcsIHZhbHVlOiBmbXRVc2Qo"
        "dS5jb3N0X3VzZCksIHRpdGxlOiAn5Lyw566X6LS555SoIFVTRCcgfSkgOiBudWxsLAogICAgICAg"
        "ICAgICAgIG11bHRpID8ganN4KCdzcGFuJywgeyBjbGFzc05hbWU6ICd3aGl0ZXNwYWNlLW5vd3Jh"
        "cCB0ZXh0LVswLjY4NzVyZW1dIHRleHQtKC0tdWktdGV4dC10ZXJ0aWFyeSknLCBjaGlsZHJlbjog"
        "J8K3ICcgKyBtb2RlbHMubGVuZ3RoICsgJyDkuKrmqKHlnosnIH0pIDogbnVsbAogICAgICAgICAg"
        "ICBdCiAgICAgICAgICB9KSwKICAgICAgbXVsdGkKICAgICAgICA/IGpzeHMoJ2RpdicsIHsKICAg"
        "ICAgICAgICAgY2xhc3NOYW1lOiAnZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTIgb3ZlcmZsb3ctaGlk"
        "ZGVuJywKICAgICAgICAgICAgY2hpbGRyZW46IFsKICAgICAgICAgICAgICBqc3goJ3NwYW4nLCB7"
        "IGNsYXNzTmFtZTogJ3doaXRlc3BhY2Utbm93cmFwIHRleHQtWzAuNjg3NXJlbV0gdGV4dC0oLS11"
        "aS10ZXh0LXF1YXRlcm5hcnkpJywgY2hpbGRyZW46ICfmnKzkvJror53mjInmqKHlnos6JyB9KSwK"
        "ICAgICAgICAgICAgICBtb2RlbHMubWFwKG1tID0+IGpzeHMoJ3NwYW4nLCB7CiAgICAgICAgICAg"
        "ICAgICBjbGFzc05hbWU6ICdpbmxpbmUtZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTEgd2hpdGVzcGFj"
        "ZS1ub3dyYXAgcm91bmRlZCBiZy0oLS11aS1iZy1lbGV2YXRlZCkgcHgtMS41IHB5LXB4IHRleHQt"
        "WzAuNjg3NXJlbV0nLAogICAgICAgICAgICAgICAgdGl0bGU6IChtbS5wcm92aWRlciA/IG1tLnBy"
        "b3ZpZGVyICsgJyDCtyAnIDogJycpICsgKG1tLm1vZGVsIHx8ICcnKSArICcgwrcg5oC7ICcgKyAo"
        "bW0udG90YWwgIT0gbnVsbCA/IG1tLnRvdGFsLnRvTG9jYWxlU3RyaW5nKCkgOiAnJykgKyAnIMK3"
        "ICcgKyAobW0uY2FsbHMgfHwgMCkgKyAnIOasoeiwg+eUqCcsCiAgICAgICAgICAgICAgICBjaGls"
        "ZHJlbjogWwogICAgICAgICAgICAgICAgICBqc3goJ3NwYW4nLCB7IGNsYXNzTmFtZTogJ3RleHQt"
        "KC0tdWktdGV4dC1zZWNvbmRhcnkpJywgY2hpbGRyZW46IG1vZGVsU2hvcnQobW0ubW9kZWwpIH0p"
        "LAogICAgICAgICAgICAgICAgICBqc3goJ3NwYW4nLCB7IGNsYXNzTmFtZTogJ2ZvbnQtbWVkaXVt"
        "IHRhYnVsYXItbnVtcyB0ZXh0LSgtLXVpLXRleHQtdGVydGlhcnkpJywgY2hpbGRyZW46IGZtdCht"
        "bS50b3RhbCkgfSkKICAgICAgICAgICAgICAgIF0KICAgICAgICAgICAgICB9LCAobW0ubW9kZWwg"
        "fHwgJycpICsgJ8K3JyArIFN0cmluZyhtbS5jYWxscykpKQogICAgICAgICAgICBdCiAgICAgICAg"
        "ICB9KQogICAgICAgIDogbnVsbAogICAgXQogIH0pCn0KCi8qIC0tLS0tLS0tLS0gZGV0YWlsIHBh"
        "Z2UgKC91c2FnZSkg4oCUIHJlYWRzIHN0YXRlLmRiIHZpYSBiYWNrZW5kIC0tLS0tLS0tLS0gKi8K"
        "ZnVuY3Rpb24gU3RhdENhcmQoeyBsYWJlbCwgdmFsdWUsIHN1YiwgYWNjZW50IH0pIHsKICByZXR1"
        "cm4ganN4cygnZGl2JywgewogICAgY2xhc3NOYW1lOiAnZmxleCBmbGV4LWNvbCBnYXAtMSByb3Vu"
        "ZGVkLW1kIGJvcmRlciBib3JkZXItKC0tdWktc3Ryb2tlLXNlY29uZGFyeSkgYmctKC0tdWktYmct"
        "ZWxldmF0ZWQpIHAtMycsCiAgICBjaGlsZHJlbjogWwogICAgICBqc3goJ2RpdicsIHsgY2xhc3NO"
        "YW1lOiAndGV4dC1bMC42ODc1cmVtXSB1cHBlcmNhc2UgdHJhY2tpbmctd2lkZSB0ZXh0LSgtLXVp"
        "LXRleHQtdGVydGlhcnkpJywgY2hpbGRyZW46IGxhYmVsIH0pLAogICAgICBqc3goJ2RpdicsIHsK"
        "ICAgICAgICBjbGFzc05hbWU6IGFjY2VudCA/ICd0ZXh0LXhsIGZvbnQtc2VtaWJvbGQgdGV4dC0o"
        "LS11aS1hY2NlbnQpJyA6ICd0ZXh0LXhsIGZvbnQtc2VtaWJvbGQgdGFidWxhci1udW1zJywKICAg"
        "ICAgICB0aXRsZTogdmFsdWUsCiAgICAgICAgY2hpbGRyZW46IHZhbHVlCiAgICAgIH0pLAogICAg"
        "ICBzdWIgPyBqc3goJ2RpdicsIHsgY2xhc3NOYW1lOiAndGV4dC1bMC42ODc1cmVtXSB0ZXh0LSgt"
        "LXVpLXRleHQtdGVydGlhcnkpJywgY2hpbGRyZW46IHN1YiB9KSA6IG51bGwKICAgIF0KICB9KQp9"
        "CgpmdW5jdGlvbiBVc2FnZVBhZ2UoeyBsb2FkIH0pIHsKICBjb25zdCBbZGF0YSwgc2V0RGF0YV0g"
        "PSB1c2VTdGF0ZShudWxsKQogIGNvbnN0IFtlcnJvciwgc2V0RXJyb3JdID0gdXNlU3RhdGUobnVs"
        "bCkKICBjb25zdCBbbG9hZGluZywgc2V0TG9hZGluZ10gPSB1c2VTdGF0ZSh0cnVlKQogIGNvbnN0"
        "IFthc29mLCBzZXRBc29mXSA9IHVzZVN0YXRlKG51bGwpCiAgY29uc3QgW3JlbG9hZEtleSwgc2V0"
        "UmVsb2FkS2V5XSA9IHVzZVN0YXRlKDApCgogIHVzZUVmZmVjdCgoKSA9PiB7CiAgICBsZXQgYWxp"
        "dmUgPSB0cnVlCiAgICBjb25zdCBydW4gPSAoKSA9PiB7CiAgICAgIGxvYWQoKS50aGVuKHJlcyA9"
        "PiB7CiAgICAgICAgaWYgKCFhbGl2ZSkgcmV0dXJuCiAgICAgICAgc2V0RGF0YShyZXMpCiAgICAg"
        "ICAgc2V0RXJyb3IocmVzICYmIHJlcy5vayA9PT0gZmFsc2UgPyAocmVzLmVycm9yIHx8ICd1c2Fn"
        "ZSBiYWNrZW5kIGVycm9yJykgOiBudWxsKQogICAgICAgIHNldEFzb2YobmV3IERhdGUoKSkKICAg"
        "ICAgfSkuY2F0Y2goZSA9PiB7CiAgICAgICAgaWYgKCFhbGl2ZSkgcmV0dXJuCiAgICAgICAgc2V0"
        "RGF0YShudWxsKQogICAgICAgIHNldEVycm9yKChlICYmIGUubWVzc2FnZSkgfHwgU3RyaW5nKGUp"
        "KQogICAgICB9KS5maW5hbGx5KCgpID0+IHsgaWYgKGFsaXZlKSBzZXRMb2FkaW5nKGZhbHNlKSB9"
        "KQogICAgfQogICAgcnVuKCkKICAgIGNvbnN0IGlkID0gc2V0SW50ZXJ2YWwocnVuLCBSRUZSRVNI"
        "X01TKQogICAgcmV0dXJuICgpID0+IHsgYWxpdmUgPSBmYWxzZTsgY2xlYXJJbnRlcnZhbChpZCkg"
        "fQogIH0sIFtsb2FkLCByZWxvYWRLZXldKQoKICBpZiAobG9hZGluZyAmJiAhZGF0YSAmJiAhZXJy"
        "b3IpIHsKICAgIHJldHVybiBqc3goJ2RpdicsIHsgY2xhc3NOYW1lOiAnZmxleCBoLWZ1bGwgaXRl"
        "bXMtY2VudGVyIGp1c3RpZnktY2VudGVyIHAtOCB0ZXh0LXNtIHRleHQtKC0tdWktdGV4dC10ZXJ0"
        "aWFyeSknLCBjaGlsZHJlbjogJ+WKoOi9veeUqOmHj+aVsOaNruKApicgfSkKICB9CiAgaWYgKGVy"
        "cm9yKSB7CiAgICByZXR1cm4ganN4cygnZGl2JywgewogICAgICBjbGFzc05hbWU6ICdmbGV4IGgt"
        "ZnVsbCBmbGV4LWNvbCBpdGVtcy1zdGFydCBqdXN0aWZ5LWNlbnRlciBnYXAtMyBwLTgnLAogICAg"
        "ICBjaGlsZHJlbjogWwogICAgICAgIGpzeCgnZGl2JywgeyBjbGFzc05hbWU6ICd0ZXh0LXNtIGZv"
        "bnQtbWVkaXVtJywgY2hpbGRyZW46ICfml6Dms5Xor7vlj5bnlKjph4/lkI7nq68nIH0pLAogICAg"
        "ICAgIGpzeCgncHJlJywgeyBjbGFzc05hbWU6ICdtYXgtdy1mdWxsIHdoaXRlc3BhY2UtcHJlLXdy"
        "YXAgcm91bmRlZC1tZCBib3JkZXIgYm9yZGVyLSgtLXVpLXN0cm9rZS1zZWNvbmRhcnkpIGJnLSgt"
        "LXVpLWJnLWVsZXZhdGVkKSBwLTMgdGV4dC14cyB0ZXh0LSgtLXVpLXRleHQtc2Vjb25kYXJ5KScs"
        "IGNoaWxkcmVuOiBlcnJvciB9KSwKICAgICAgICBqc3goJ2RpdicsIHsgY2xhc3NOYW1lOiAndGV4"
        "dC14cyB0ZXh0LSgtLXVpLXRleHQtdGVydGlhcnkpJywgY2hpbGRyZW46ICflkI7nq6/pnIDliqDl"
        "haUgcGx1Z2lucy5lbmFibGVkIOeZveWQjeWNleW5tuWcqCBnYXRld2F5IOmHjeWQr+WQjuaMgui9"
        "veOAguW6lemDqOadoSjlrp7ml7Yp5LiN5L6d6LWW5a6D77yM5pys6aG1KOWOhuWPsinkvp3otZbl"
        "roPjgIInIH0pLAogICAgICAgIGpzeCgnYnV0dG9uJywgewogICAgICAgICAgdHlwZTogJ2J1dHRv"
        "bicsCiAgICAgICAgICBjbGFzc05hbWU6ICdyb3VuZGVkLW1kIGJnLSgtLXVpLWFjY2VudCkgcHgt"
        "MyBweS0xLjUgdGV4dC1zbSBob3ZlcjpvcGFjaXR5LTkwJywKICAgICAgICAgIG9uQ2xpY2s6ICgp"
        "ID0+IHsgc2V0UmVsb2FkS2V5KGsgPT4gayArIDEpOyBzZXRMb2FkaW5nKHRydWUpIH0sCiAgICAg"
        "ICAgICBjaGlsZHJlbjogJ+mHjeivlScKICAgICAgICB9KQogICAgICBdCiAgICB9KQogIH0KCiAg"
        "Y29uc3QgdCA9IChkYXRhICYmIGRhdGEudG90YWxzKSB8fCB7fQogIGNvbnN0IG1ldGEgPSAoZGF0"
        "YSAmJiBkYXRhLm1ldGEpIHx8IHt9CiAgY29uc3QgcGVyTW9kZWwgPSAoZGF0YSAmJiBkYXRhLnBl"
        "cl9tb2RlbCkgfHwgW10KICBjb25zdCBwZXJTZXNzaW9uID0gKGRhdGEgJiYgZGF0YS5wZXJfc2Vz"
        "c2lvbikgfHwgW10KICBjb25zdCBkYWlseSA9ICgoZGF0YSAmJiBkYXRhLmRhaWx5KSB8fCBbXSku"
        "ZmlsdGVyKGQgPT4gZC5hY3RpdmUpCiAgY29uc3QgY2FjaGVSYXRpbyA9IHQuY2FjaGVfc2hhcmVf"
        "b2ZfaW5wdXQKCiAgcmV0dXJuIGpzeHMoJ2RpdicsIHsKICAgIGNsYXNzTmFtZTogJ2ZsZXggaC1m"
        "dWxsIGZsZXgtY29sIGdhcC00IG92ZXJmbG93LXktYXV0byBwLTQnLAogICAgY2hpbGRyZW46IFsK"
        "ICAgICAganN4cygnZGl2JywgewogICAgICAgIGNsYXNzTmFtZTogJ2ZsZXggZmxleC13cmFwIGl0"
        "ZW1zLWNlbnRlciBnYXAtMycsCiAgICAgICAgY2hpbGRyZW46IFsKICAgICAgICAgIGpzeCgnZGl2"
        "JywgeyBjbGFzc05hbWU6ICd0ZXh0LWJhc2UgZm9udC1zZW1pYm9sZCcsIGNoaWxkcmVuOiAnVG9r"
        "ZW4g55So6YePJyB9KSwKICAgICAgICAgIGpzeCgnc3BhbicsIHsgY2xhc3NOYW1lOiAncm91bmRl"
        "ZCBiZy0oLS11aS1iZy1lbGV2YXRlZCkgcHgtMS41IHB5LTAuNSB0ZXh0LVswLjY4NzVyZW1dIHRl"
        "eHQtKC0tdWktdGV4dC1zZWNvbmRhcnkpJywKICAgICAgICAgICAgY2hpbGRyZW46IGAke21ldGEu"
        "bW9kZWxzIHx8IDB9IG1vZGVscyDCtyAke21ldGEuc2Vzc2lvbnMgfHwgMH0gc2Vzc2lvbnMgwrcg"
        "JHttZXRhLmFwaV9jYWxscyB8fCAwfSBjYWxsc2AgfSksCiAgICAgICAgICBqc3goJ3NwYW4nLCB7"
        "IGNsYXNzTmFtZTogJ3RleHQtWzAuNjg3NXJlbV0gdGV4dC0oLS11aS10ZXh0LXRlcnRpYXJ5KScs"
        "CiAgICAgICAgICAgIGNoaWxkcmVuOiBhc29mID8gJ+abtOaWsOS6jiAnICsgZm10RGF0ZShhc29m"
        "LmdldFRpbWUoKSAvIDEwMDApIDogJycgfSksCiAgICAgICAgICBqc3goJ2J1dHRvbicsIHsKICAg"
        "ICAgICAgICAgdHlwZTogJ2J1dHRvbicsCiAgICAgICAgICAgIGNsYXNzTmFtZTogJ21sLWF1dG8g"
        "cm91bmRlZC1tZCBib3JkZXIgYm9yZGVyLSgtLXVpLXN0cm9rZS1zZWNvbmRhcnkpIHB4LTIgcHkt"
        "MSB0ZXh0LXhzIGhvdmVyOmJnLSgtLWNocm9tZS1hY3Rpb24taG92ZXIpJywKICAgICAgICAgICAg"
        "b25DbGljazogKCkgPT4geyBzZXRSZWxvYWRLZXkoayA9PiBrICsgMSk7IHNldExvYWRpbmcodHJ1"
        "ZSkgfSwKICAgICAgICAgICAgY2hpbGRyZW46ICfliLfmlrAnCiAgICAgICAgICB9KQogICAgICAg"
        "IF0KICAgICAgfSksCiAgICAgIGpzeHMoJ2RpdicsIHsKICAgICAgICBjbGFzc05hbWU6ICdncmlk"
        "IGdyaWQtY29scy0yIGdhcC0yIG1kOmdyaWQtY29scy00JywKICAgICAgICBjaGlsZHJlbjogWwog"
        "ICAgICAgICAganN4KFN0YXRDYXJkLCB7IGxhYmVsOiAn5oC7IFRva2VuJywgdmFsdWU6IGZtdCh0"
        "LnRvdGFsKSwgc3ViOiBTdHJpbmcodC50b3RhbCA/PyAnJyksIGFjY2VudDogdHJ1ZSB9KSwKICAg"
        "ICAgICAgIGpzeChTdGF0Q2FyZCwgeyBsYWJlbDogJ+i+k+WFpScsIHZhbHVlOiBmbXQodC5pbnB1"
        "dCksIHN1YjogU3RyaW5nKHQuaW5wdXQgPz8gJycpIH0pLAogICAgICAgICAganN4KFN0YXRDYXJk"
        "LCB7IGxhYmVsOiAn6L6T5Ye6JywgdmFsdWU6IGZtdCh0Lm91dHB1dCksIHN1YjogU3RyaW5nKHQu"
        "b3V0cHV0ID8/ICcnKSB9KSwKICAgICAgICAgIGpzeChTdGF0Q2FyZCwgeyBsYWJlbDogJ+e8k+Wt"
        "mOivu+WPlicsIHZhbHVlOiBmbXQodC5jYWNoZV9yZWFkKSwgc3ViOiBTdHJpbmcodC5jYWNoZV9y"
        "ZWFkID8/ICcnKSB9KSwKICAgICAgICAgIGpzeChTdGF0Q2FyZCwgeyBsYWJlbDogJ+aOqOeQhics"
        "IHZhbHVlOiBmbXQodC5yZWFzb25pbmcpLCBzdWI6IFN0cmluZyh0LnJlYXNvbmluZyA/PyAnJykg"
        "fSksCiAgICAgICAgICBqc3goU3RhdENhcmQsIHsgbGFiZWw6ICfkvLDnrpfotLnnlKgnLCB2YWx1"
        "ZTogZm10VXNkKHQuZXN0X3VzZCksIHN1YjogYCR7bWV0YS5lc3Rfcm93cyB8fCAwfSDot6/nlLHo"
        "rqHlhaXotLnnjodgLCBhY2NlbnQ6IHRydWUgfSksCiAgICAgICAgICBqc3goU3RhdENhcmQsIHsg"
        "bGFiZWw6ICdBUEkg6LCD55SoJywgdmFsdWU6IGZtdCh0LmFwaV9jYWxscyksIHN1YjogJycgfSks"
        "CiAgICAgICAgICBqc3goU3RhdENhcmQsIHsgbGFiZWw6ICfnvJPlrZggw7cg6L6T5YWlJywgdmFs"
        "dWU6IGNhY2hlUmF0aW8gPT0gbnVsbCA/ICfigJQnIDogY2FjaGVSYXRpby50b0ZpeGVkKDEpICsg"
        "J3gnLAogICAgICAgICAgICBzdWI6IGNhY2hlUmF0aW8gPT0gbnVsbCA/ICfml6DmlbDmja4nIDog"
        "J+ivu+WPluaUvuWkp+WAjeaVsO+8iOmdnuWRveS4reeOh++8iScgfSkKICAgICAgICBdCiAgICAg"
        "IH0pLAogICAgICBqc3hzKCdkaXYnLCB7CiAgICAgICAgY2xhc3NOYW1lOiAncm91bmRlZC1tZCBi"
        "b3JkZXIgYm9yZGVyLSgtLXVpLXN0cm9rZS1zZWNvbmRhcnkpIGJnLSgtLXVpLWJnLWVsZXZhdGVk"
        "KSBwLTMnLAogICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICBqc3hzKCdkaXYnLCB7IGNsYXNz"
        "TmFtZTogJ21iLTIgZmxleCBpdGVtcy1iYXNlbGluZSBnYXAtMicsCiAgICAgICAgICAgIGNoaWxk"
        "cmVuOiBbIGpzeCgnZGl2JywgeyBjbGFzc05hbWU6ICd0ZXh0LXNtIGZvbnQtbWVkaXVtJywgY2hp"
        "bGRyZW46ICfov5EgMzAg5aSp6LaL5Yq/JyB9KSwKICAgICAgICAgICAgICBqc3goJ3NwYW4nLCB7"
        "IGNsYXNzTmFtZTogJ3RleHQtWzAuNjg3NXJlbV0gdGV4dC0oLS11aS10ZXh0LXRlcnRpYXJ5KScs"
        "IGNoaWxkcmVuOiBgJHtkYWlseS5sZW5ndGh9IOS4quaciemHj+aXpWAgfSkgXSB9KSwKICAgICAg"
        "ICAgIGRhaWx5Lmxlbmd0aCA9PT0gMAogICAgICAgICAgICA/IGpzeCgnZGl2JywgeyBjbGFzc05h"
        "bWU6ICdweS00IHRleHQtY2VudGVyIHRleHQtWzAuODEyNXJlbV0gdGV4dC0oLS11aS10ZXh0LXRl"
        "cnRpYXJ5KScsIGNoaWxkcmVuOiAn6L+RIDMwIOWkqeayoeacieeUqOmHj+iusOW9lScgfSkKICAg"
        "ICAgICAgICAgOiBqc3hzKCdkaXYnLCB7CiAgICAgICAgICAgICAgICBjbGFzc05hbWU6ICdmbGV4"
        "IGZsZXgtY29sIGdhcC0xJywKICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBkYWlseS5zbGljZSgt"
        "MTQpLm1hcChkID0+IHsKICAgICAgICAgICAgICAgICAgY29uc3QgbXggPSBNYXRoLm1heCguLi5k"
        "YWlseS5tYXAoeCA9PiB4LnRvdGFsIHx8IDApLCAxKQogICAgICAgICAgICAgICAgICByZXR1cm4g"
        "anN4cygnZGl2JywgewogICAgICAgICAgICAgICAgICAgIGNsYXNzTmFtZTogJ2ZsZXggaXRlbXMt"
        "Y2VudGVyIGdhcC0yJywKICAgICAgICAgICAgICAgICAgICBjaGlsZHJlbjogWwogICAgICAgICAg"
        "ICAgICAgICAgICAganN4KCdzcGFuJywgeyBjbGFzc05hbWU6ICd3LTE2IHNocmluay0wIHRleHQt"
        "WzAuNjg3NXJlbV0gdGFidWxhci1udW1zIHRleHQtKC0tdWktdGV4dC10ZXJ0aWFyeSknLCBjaGls"
        "ZHJlbjogZC5kYXRlLnNsaWNlKDUpIH0pLAogICAgICAgICAgICAgICAgICAgICAganN4KCdkaXYn"
        "LCB7IGNsYXNzTmFtZTogJ2ZsZXggZmxleC0xIGdhcC0wLjUnLAogICAgICAgICAgICAgICAgICAg"
        "ICAgICBjaGlsZHJlbjogWwogICAgICAgICAgICAgICAgICAgICAgICAgIGpzeCgnZGl2JywgeyBj"
        "bGFzc05hbWU6ICdoLTIgcm91bmRlZC1zbSBiZy0oLS11aS1hY2NlbnQpIG9wYWNpdHktNjAnLCBz"
        "dHlsZTogeyB3aWR0aDogTWF0aC5tYXgoKGQuY2FjaGVfcmVhZCB8fCAwKSAvIG14LCAwLjAwNCkg"
        "KiAxMDAgKyAnJScgfSB9KSwKICAgICAgICAgICAgICAgICAgICAgICAgICBqc3goJ2RpdicsIHsg"
        "Y2xhc3NOYW1lOiAnaC0yIHJvdW5kZWQtc20gYmctKC0tdWktYWNjZW50KScsIHN0eWxlOiB7IHdp"
        "ZHRoOiBNYXRoLm1heCgoZC5vdXRwdXQgfHwgMCkgLyBteCwgMC4wMDQpICogMTAwICsgJyUnIH0g"
        "fSkKICAgICAgICAgICAgICAgICAgICAgICAgXSB9KSwKICAgICAgICAgICAgICAgICAgICAgIGpz"
        "eCgnc3BhbicsIHsgY2xhc3NOYW1lOiAndy0xNCBzaHJpbmstMCB0ZXh0LXJpZ2h0IHRleHQtWzAu"
        "Njg3NXJlbV0gdGFidWxhci1udW1zIHRleHQtKC0tdWktdGV4dC1zZWNvbmRhcnkpJywgdGl0bGU6"
        "ICd0b3RhbCAnICsgKGQudG90YWwgPz8gMCksIGNoaWxkcmVuOiBmbXQoZC50b3RhbCkgfSkKICAg"
        "ICAgICAgICAgICAgICAgICBdCiAgICAgICAgICAgICAgICAgIH0sIGQuZGF0ZSkKICAgICAgICAg"
        "ICAgICAgIH0pCiAgICAgICAgICAgICAgfSkKICAgICAgICBdCiAgICAgIH0pLAogICAgICBqc3hz"
        "KCdkaXYnLCB7CiAgICAgICAgY2xhc3NOYW1lOiAncm91bmRlZC1tZCBib3JkZXIgYm9yZGVyLSgt"
        "LXVpLXN0cm9rZS1zZWNvbmRhcnkpIGJnLSgtLXVpLWJnLWVsZXZhdGVkKSBwLTMnLAogICAgICAg"
        "IGNoaWxkcmVuOiBbCiAgICAgICAgICBqc3goJ2RpdicsIHsgY2xhc3NOYW1lOiAnbWItMiB0ZXh0"
        "LXNtIGZvbnQtbWVkaXVtJywgY2hpbGRyZW46ICfmjInmqKHlnosnIH0pLAogICAgICAgICAgcGVy"
        "TW9kZWwubGVuZ3RoID09PSAwCiAgICAgICAgICAgID8ganN4KCdkaXYnLCB7IGNsYXNzTmFtZTog"
        "J3B5LTMgdGV4dC1jZW50ZXIgdGV4dC1bMC44MTI1cmVtXSB0ZXh0LSgtLXVpLXRleHQtdGVydGlh"
        "cnkpJywgY2hpbGRyZW46ICfmmoLml6DmlbDmja4nIH0pCiAgICAgICAgICAgIDoganN4KCd0YWJs"
        "ZScsIHsKICAgICAgICAgICAgICAgIGNsYXNzTmFtZTogJ3ctZnVsbCBib3JkZXItY29sbGFwc2Ug"
        "dGV4dC1bMC44MTI1cmVtXScsCiAgICAgICAgICAgICAgICBjaGlsZHJlbjoganN4cygndGJvZHkn"
        "LCB7CiAgICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBwZXJNb2RlbC5tYXAoKG0sIGkpID0+IGpz"
        "eHMoJ3RyJywgewogICAgICAgICAgICAgICAgICAgIGNsYXNzTmFtZTogJ2JvcmRlci1iIGJvcmRl"
        "ci0oLS11aS1zdHJva2Utc2Vjb25kYXJ5KSBsYXN0OmJvcmRlci0wJywKICAgICAgICAgICAgICAg"
        "ICAgICBjaGlsZHJlbjogWwogICAgICAgICAgICAgICAgICAgICAganN4KCd0ZCcsIHsgY2xhc3NO"
        "YW1lOiAncHktMS41IHByLTInLCBjaGlsZHJlbjoganN4cygnZGl2JywgeyBjbGFzc05hbWU6ICdm"
        "bGV4IGZsZXgtY29sJywKICAgICAgICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFsKICAgICAg"
        "ICAgICAgICAgICAgICAgICAgICBqc3goJ3NwYW4nLCB7IGNsYXNzTmFtZTogJ2ZvbnQtbWVkaXVt"
        "JywgY2hpbGRyZW46IG0ubW9kZWwgfHwgJ+KAlCcgfSksCiAgICAgICAgICAgICAgICAgICAgICAg"
        "ICAgbS5wcm92aWRlciA/IGpzeCgnc3BhbicsIHsgY2xhc3NOYW1lOiAndGV4dC1bMC42ODc1cmVt"
        "XSB0ZXh0LSgtLXVpLXRleHQtdGVydGlhcnkpJywgY2hpbGRyZW46IG0ucHJvdmlkZXIgfSkgOiBu"
        "dWxsCiAgICAgICAgICAgICAgICAgICAgICAgIF0gfSkgfSksCiAgICAgICAgICAgICAgICAgICAg"
        "ICB0YyhtLmNhbGxzLCAn6LCD55SoJyksCiAgICAgICAgICAgICAgICAgICAgICB0YyhtLmlucHV0"
        "LCAn6L6T5YWlJyksCiAgICAgICAgICAgICAgICAgICAgICB0YyhtLm91dHB1dCwgJ+i+k+WHuicp"
        "LAogICAgICAgICAgICAgICAgICAgICAgdGMobS5jYWNoZV9yZWFkLCAn57yT5a2YJyksCiAgICAg"
        "ICAgICAgICAgICAgICAgICB0YyhtLnJlYXNvbmluZywgJ+aOqOeQhicpLAogICAgICAgICAgICAg"
        "ICAgICAgICAgdGMobS5lc3RfdXNkID09IG51bGwgPyBudWxsIDogZm10VXNkKG0uZXN0X3VzZCks"
        "ICfotLnnlKgnKQogICAgICAgICAgICAgICAgICAgIF0KICAgICAgICAgICAgICAgICAgfSwgKG0u"
        "cHJvdmlkZXIgfHwgJycpICsgJ8K3JyArIChtLm1vZGVsIHx8ICcnKSArICfCtycgKyBpKSkKICAg"
        "ICAgICAgICAgICAgIH0pCiAgICAgICAgICAgICAgfSkKICAgICAgICBdCiAgICAgIH0pLAogICAg"
        "ICBqc3hzKCdkaXYnLCB7CiAgICAgICAgY2xhc3NOYW1lOiAncm91bmRlZC1tZCBib3JkZXIgYm9y"
        "ZGVyLSgtLXVpLXN0cm9rZS1zZWNvbmRhcnkpIGJnLSgtLXVpLWJnLWVsZXZhdGVkKSBwLTMnLAog"
        "ICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICBqc3goJ2RpdicsIHsgY2xhc3NOYW1lOiAnbWIt"
        "MiB0ZXh0LXNtIGZvbnQtbWVkaXVtJywgY2hpbGRyZW46ICfmjInkvJror53vvIhUb3AgMzDvvIkn"
        "IH0pLAogICAgICAgICAgcGVyU2Vzc2lvbi5sZW5ndGggPT09IDAKICAgICAgICAgICAgPyBqc3go"
        "J2RpdicsIHsgY2xhc3NOYW1lOiAncHktMyB0ZXh0LWNlbnRlciB0ZXh0LVswLjgxMjVyZW1dIHRl"
        "eHQtKC0tdWktdGV4dC10ZXJ0aWFyeSknLCBjaGlsZHJlbjogJ+aaguaXoOaVsOaNricgfSkKICAg"
        "ICAgICAgICAgOiBqc3goJ3RhYmxlJywgewogICAgICAgICAgICAgICAgY2xhc3NOYW1lOiAndy1m"
        "dWxsIGJvcmRlci1jb2xsYXBzZSB0ZXh0LVswLjgxMjVyZW1dJywKICAgICAgICAgICAgICAgIGNo"
        "aWxkcmVuOiBqc3hzKCd0Ym9keScsIHsKICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IHBlclNl"
        "c3Npb24ubWFwKChzLCBpKSA9PiBqc3hzKCd0cicsIHsKICAgICAgICAgICAgICAgICAgICBjbGFz"
        "c05hbWU6ICdib3JkZXItYiBib3JkZXItKC0tdWktc3Ryb2tlLXNlY29uZGFyeSkgbGFzdDpib3Jk"
        "ZXItMCcsCiAgICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFsKICAgICAgICAgICAgICAgICAg"
        "ICAgIGpzeCgndGQnLCB7IGNsYXNzTmFtZTogJ21heC13LVsyNDBweF0gcHktMS41IHByLTInLCBj"
        "aGlsZHJlbjoganN4cygnZGl2JywgeyBjbGFzc05hbWU6ICdmbGV4IGZsZXgtY29sJywKICAgICAg"
        "ICAgICAgICAgICAgICAgICAgY2hpbGRyZW46IFsKICAgICAgICAgICAgICAgICAgICAgICAgICBq"
        "c3goJ3NwYW4nLCB7IGNsYXNzTmFtZTogJ3RydW5jYXRlIGZvbnQtbWVkaXVtJywgdGl0bGU6IHMu"
        "dGl0bGUgfHwgcy5zZXNzaW9uX2lkLCBjaGlsZHJlbjogcy50aXRsZSB8fCBzLnNlc3Npb25faWQg"
        "fSksCiAgICAgICAgICAgICAgICAgICAgICAgICAganN4KCdzcGFuJywgeyBjbGFzc05hbWU6ICd0"
        "ZXh0LVswLjY4NzVyZW1dIHRleHQtKC0tdWktdGV4dC10ZXJ0aWFyeSknLAogICAgICAgICAgICAg"
        "ICAgICAgICAgICAgICAgY2hpbGRyZW46IChzLm1vZGVsIHx8ICcnKSArIChzLnByb3ZpZGVyID8g"
        "JyDCtyAnICsgcy5wcm92aWRlciA6ICcnKSArICcgwrcgJyArIGZtdERhdGUocy5sYXN0X2FjdGl2"
        "aXR5X2F0IHx8IHMuc3RhcnRlZF9hdCkgfSkKICAgICAgICAgICAgICAgICAgICAgICAgXSB9KSB9"
        "KSwKICAgICAgICAgICAgICAgICAgICAgIHRjKHMuY2FsbHMsICfosIPnlKgnKSwKICAgICAgICAg"
        "ICAgICAgICAgICAgIHRjKHMudG90YWwsICfmgLsnKSwKICAgICAgICAgICAgICAgICAgICAgIHRj"
        "KHMuaW5wdXQsICfovpPlhaUnKSwKICAgICAgICAgICAgICAgICAgICAgIHRjKHMub3V0cHV0LCAn"
        "6L6T5Ye6JyksCiAgICAgICAgICAgICAgICAgICAgICB0YyhzLmNhY2hlX3JlYWQsICfnvJPlrZgn"
        "KSwKICAgICAgICAgICAgICAgICAgICAgIHRjKHMuZXN0X3VzZCA9PSBudWxsID8gbnVsbCA6IGZt"
        "dFVzZChzLmVzdF91c2QpLCAn6LS555SoJykKICAgICAgICAgICAgICAgICAgICBdCiAgICAgICAg"
        "ICAgICAgICAgIH0sIChzLnNlc3Npb25faWQgfHwgJ3MnKSArICfCtycgKyBpKSkKICAgICAgICAg"
        "ICAgICAgIH0pCiAgICAgICAgICAgICAgfSkKICAgICAgICBdCiAgICAgIH0pCiAgICBdCiAgfSkK"
        "fQoKZnVuY3Rpb24gdGModiwgbGFiZWwpIHsKICByZXR1cm4ganN4KCd0ZCcsIHsKICAgIGNsYXNz"
        "TmFtZTogJ3B5LTEuNSBweC0xIHRleHQtcmlnaHQgdGFidWxhci1udW1zIHRleHQtKC0tdWktdGV4"
        "dC1zZWNvbmRhcnkpJywKICAgIHRpdGxlOiBsYWJlbCwKICAgIGNoaWxkcmVuOiB2ID09IG51bGwg"
        "PyAn4oCUJyA6IHYKICB9KQp9CgovKiAtLS0tLS0tLS0tIHBsdWdpbiBleHBvcnQgLS0tLS0tLS0t"
        "LSAqLwpleHBvcnQgZGVmYXVsdCB7CiAgaWQ6IElELAogIG5hbWU6ICdUb2tlbiDnlKjph48nLAog"
        "IHJlZ2lzdGVyKGN0eCkgewogICAgY29uc3QgbG9hZCA9ICgpID0+IGN0eC5yZXN0KCcvb3ZlcnZp"
        "ZXcnKQogICAgY29uc3QgbG9hZE1vZGVscyA9IHNpZCA9PiBjdHgucmVzdCgnL3Nlc3Npb25fbW9k"
        "ZWxzP3Nlc3Npb25faWQ9JyArIGVuY29kZVVSSUNvbXBvbmVudChTdHJpbmcoc2lkIHx8ICcnKSkp"
        "CgogICAgLy8gQWx3YXlzLXZpc2libGUgYm90dG9tIG1ldGVyIChhdXRvLWRvY2tlZCBiZWxvdyB0"
        "aGUgd29ya3NwYWNlIHBhbmUpLgogICAgY3R4LnJlZ2lzdGVyKHsKICAgICAgaWQ6ICdwYW5lJywK"
        "ICAgICAgYXJlYTogUEFORVNfQVJFQSwKICAgICAgdGl0bGU6ICdUb2tlbiDnlKjph48nLAogICAg"
        "ICBkYXRhOiB7IHBsYWNlbWVudDogJ2JvdHRvbScsIGRvY2s6IHsgcGFuZTogJ3dvcmtzcGFjZScs"
        "IHBvczogJ2JvdHRvbScgfSwgaGVpZ2h0OiAnNTZweCcgfSwKICAgICAgcmVuZGVyOiAoKSA9PiBq"
        "c3goQm90dG9tQmFyLCB7IGxvYWRNb2RlbHMgfSkKICAgIH0pCgogICAgLy8gRGV0YWlsIHBhZ2Ug"
        "KGNsaWNraW5nIHRoZSBiYXIgb3BlbnMgaXQpLgogICAgY3R4LnJlZ2lzdGVyKHsKICAgICAgaWQ6"
        "ICdwYWdlJywKICAgICAgYXJlYTogUk9VVEVTX0FSRUEsCiAgICAgIGRhdGE6IHsgcGF0aDogJy91"
        "c2FnZScgfSwKICAgICAgcmVuZGVyOiAoKSA9PiBqc3goVXNhZ2VQYWdlLCB7IGxvYWQgfSkKICAg"
        "IH0pCgogICAgY3R4LnJlZ2lzdGVyKHsKICAgICAgaWQ6ICdvcGVuJywKICAgICAgYXJlYTogUEFM"
        "RVRURV9BUkVBLAogICAgICBkYXRhOiB7CiAgICAgICAgaWQ6ICdoZXJtZXMtdXNhZ2Uub3Blbics"
        "CiAgICAgICAgbGFiZWw6ICfmiZPlvIAgVG9rZW4g55So6YePJywKICAgICAgICBrZXl3b3Jkczog"
        "Wyd1c2FnZScsICd0b2tlbicsICfnlKjph48nXSwKICAgICAgICBydW46ICgpID0+IHsgaGFwdGlj"
        "KCd0YXAnKTsgaG9zdC5uYXZpZ2F0ZSgnL3VzYWdlJykgfQogICAgICB9CiAgICB9KQogIH0KfQo="
    )

B64_plugins_hermes_usage_dashboard_plugin_api_py = (
        "IiIiSGVybWVzIFVzYWdlIOKAlCBwZXJzaXN0ZW50IHRva2VuLXVzYWdlIGJhY2tlbmQgKHJlYWRz"
        "IEhlcm1lcycgb3duIHN0YXRlLmRiKS4KCkEgRmFzdEFQSSByb3V0ZXIgbW91bnRlZCBhdCAvYXBp"
        "L3BsdWdpbnMvaGVybWVzLXVzYWdlLyogYnkgdGhlIGRhc2hib2FyZC9kZXNrdG9wCnBsdWdpbiBz"
        "eXN0ZW0uIEl0IGlzIHRoZSBzZXJ2ZXItc2lkZSBoYWxmIG9mIGEgImRzaC10b2tlbi11c2FnZSIt"
        "c3R5bGUgbG9jYWwKb2JzZXJ2YWJpbGl0eSB0b29sOiBpdCByZWFkcyB0aGUgU0FNRSB1c2FnZSBk"
        "YXRhIEhlcm1lcyBhbHJlYWR5IHBlcnNpc3RzIGluCnN0YXRlLmRiIChzZXNzaW9ucyArIHNlc3Np"
        "b25fbW9kZWxfdXNhZ2UpIGFuZCByZXR1cm5zIGRzaC1zdHlsZSBhZ2dyZWdhdGlvbnMg4oCUCnRv"
        "dGFscywgcGVyIHByb3ZpZGVyL21vZGVsLCBwZXIgc2Vzc2lvbiwgZGFpbHkgdHJlbmQsIGNhY2hl"
        "IHN0cnVjdHVyZSBhbmQKZXN0aW1hdGVkIGNvc3QuIEl0IG5ldmVyIHdyaXRlcyB0byB0aGUgREIg"
        "YW5kIG5ldmVyIHRvdWNoZXMgbW9kZWwgaGlzdG9yeS4KCkVudiBvdmVycmlkZSBmb3IgdGVzdGlu"
        "ZyBvbmx5OiBzZXQgSEVSTUVTX1VTQUdFX0RCIHRvIGEgc3RhdGUuZGIgcGF0aAooZS5nLiBhIGJh"
        "Y2t1cCBzbmFwc2hvdCkgdG8gcG9pbnQgdGhlIHF1ZXJpZXMgYXQgYSBjb3B5LgoiIiIKCmZyb20g"
        "X19mdXR1cmVfXyBpbXBvcnQgYW5ub3RhdGlvbnMKCmltcG9ydCBvcwppbXBvcnQgc3FsaXRlMwpp"
        "bXBvcnQgdGltZQpmcm9tIGRhdGV0aW1lIGltcG9ydCBkYXRldGltZSwgdGltZXpvbmUKZnJvbSBw"
        "YXRobGliIGltcG9ydCBQYXRoCgpmcm9tIGZhc3RhcGkgaW1wb3J0IEFQSVJvdXRlcgoKcm91dGVy"
        "ID0gQVBJUm91dGVyKCkKCiMgTWFwIG9mIFVUQyBkYXRlIHJhbmdlcyBvdmVyIHdoaWNoIGNhY2hl"
        "X3JlYWQvY2FjaGVfd3JpdGUgYXJlIGF1dGhvcml0YXRpdmUuCiMgQ2FjaGUgZmllbGRzIGFyZSBv"
        "bmx5IHN1bW1lZCB3aGVuIHRoZSBzb3VyY2Ugcm93IHBvcHVsYXRlZCB0aGVtIChzZWUgcXVlcmll"
        "cykuCgpfVVRDX0RBWSA9IDg2NDAwLjAKCgpkZWYgX3Jlc29sdmVfZGJfcGF0aCgpIC0+IFBhdGg6"
        "CiAgICBvdmVycmlkZSA9IG9zLmVudmlyb24uZ2V0KCJIRVJNRVNfVVNBR0VfREIiKQogICAgaWYg"
        "b3ZlcnJpZGU6CiAgICAgICAgcmV0dXJuIFBhdGgob3ZlcnJpZGUpCiAgICBob21lID0gb3MuZW52"
        "aXJvbi5nZXQoIkhFUk1FU19IT01FIikKICAgIGlmIG5vdCBob21lOgogICAgICAgIHRyeToKICAg"
        "ICAgICAgICAgZnJvbSBoZXJtZXNfY29uc3RhbnRzIGltcG9ydCBnZXRfcHJvY2Vzc19oZXJtZXNf"
        "aG9tZQoKICAgICAgICAgICAgaG9tZSA9IHN0cihnZXRfcHJvY2Vzc19oZXJtZXNfaG9tZSgpKQog"
        "ICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIGhvbWUgPSBOb25lCiAgICBpZiBu"
        "b3QgaG9tZToKICAgICAgICBob21lID0gc3RyKFBhdGguaG9tZSgpIC8gIi5oZXJtZXMiKQogICAg"
        "cmV0dXJuIFBhdGgoaG9tZSkgLyAic3RhdGUuZGIiCgoKZGVmIF9jb25uZWN0KGRiX3BhdGg6IFBh"
        "dGgpIC0+IHNxbGl0ZTMuQ29ubmVjdGlvbjoKICAgICIiIlJlYWQtb25seSBjb25uZWN0aW9uOyBk"
        "ZWdyYWRlcyB0byBpbW11dGFibGUgKG5vIFdBTCkgb24gbG9jayBlcnJvcnMuIiIiCiAgICB1cmkg"
        "PSBmImZpbGU6e2RiX3BhdGguYXNfcG9zaXgoKX0/bW9kZT1ybyIKICAgIHRyeToKICAgICAgICBy"
        "ZXR1cm4gc3FsaXRlMy5jb25uZWN0KHVyaSwgdXJpPVRydWUsIHRpbWVvdXQ9NSkKICAgIGV4Y2Vw"
        "dCBzcWxpdGUzLkVycm9yOgogICAgICAgIHBhc3MKICAgIHRyeToKICAgICAgICByZXR1cm4gc3Fs"
        "aXRlMy5jb25uZWN0KHVyaSArICImaW1tdXRhYmxlPTEiLCB1cmk9VHJ1ZSwgdGltZW91dD01KQog"
        "ICAgZXhjZXB0IHNxbGl0ZTMuRXJyb3I6CiAgICAgICAgIyBMYXN0IHJlc29ydDogbm9ybWFsIHJl"
        "YWQtd3JpdGUgb3BlbiAoc2FmZSBmb3IgU0VMRUNUcyBpbiBXQUwgbW9kZSkuCiAgICAgICAgcmV0"
        "dXJuIHNxbGl0ZTMuY29ubmVjdChzdHIoZGJfcGF0aCksIHRpbWVvdXQ9NSkKCgpkZWYgX2Yodik6"
        "CiAgICByZXR1cm4gTm9uZSBpZiB2IGlzIE5vbmUgZWxzZSBmbG9hdCh2KQoKCmRlZiBfbm93X3V0"
        "Y19kYXkoKSAtPiBpbnQ6CiAgICByZXR1cm4gaW50KHRpbWUudGltZSgpKSAvLyA4NjQwMAoKCkBy"
        "b3V0ZXIuZ2V0KCIvaGVhbHRoIikKYXN5bmMgZGVmIGhlYWx0aCgpOgogICAgcmV0dXJuIHsib2si"
        "OiBUcnVlLCAiZGIiOiBzdHIoX3Jlc29sdmVfZGJfcGF0aCgpKX0KCgpAcm91dGVyLmdldCgiL3Nl"
        "c3Npb25fbW9kZWxzIikKYXN5bmMgZGVmIHNlc3Npb25fbW9kZWxzKHNlc3Npb25faWQ6IHN0ciA9"
        "ICIiKToKICAgICIiIlBlci1tb2RlbCB1c2FnZSBicmVha2Rvd24gZm9yIG9uZSBzZXNzaW9uIChz"
        "ZXNzaW9uX2lkID0gZHVyYWJsZSBzZXNzaW9uIGlkKS4iIiIKICAgIGlmIG5vdCBzZXNzaW9uX2lk"
        "OgogICAgICAgIHJldHVybiB7Im9rIjogRmFsc2UsICJlcnJvciI6ICJtaXNzaW5nIHNlc3Npb25f"
        "aWQgcXVlcnkgcGFyYW0ifQogICAgZGIgPSBfcmVzb2x2ZV9kYl9wYXRoKCkKICAgIGlmIG5vdCBk"
        "Yi5leGlzdHMoKToKICAgICAgICByZXR1cm4geyJvayI6IEZhbHNlLCAiZXJyb3IiOiBmInN0YXRl"
        "LmRiIG5vdCBmb3VuZCBhdCB7ZGJ9In0KICAgIGNvbm4gPSBfY29ubmVjdChkYikKICAgIGNvbm4u"
        "cm93X2ZhY3RvcnkgPSBzcWxpdGUzLlJvdwogICAgdHJ5OgogICAgICAgIHJvd3MgPSBbCiAgICAg"
        "ICAgICAgIGRpY3QocikKICAgICAgICAgICAgZm9yIHIgaW4gY29ubi5leGVjdXRlKAogICAgICAg"
        "ICAgICAgICAgInNlbGVjdCBiaWxsaW5nX3Byb3ZpZGVyIGFzIHByb3ZpZGVyLCBtb2RlbCwgIgog"
        "ICAgICAgICAgICAgICAgInN1bShhcGlfY2FsbF9jb3VudCkgYXMgY2FsbHMsICIKICAgICAgICAg"
        "ICAgICAgICJzdW0oaW5wdXRfdG9rZW5zKSBhcyBpbnB1dCwgc3VtKG91dHB1dF90b2tlbnMpIGFz"
        "IG91dHB1dCwgIgogICAgICAgICAgICAgICAgInN1bShjYWNoZV9yZWFkX3Rva2VucykgYXMgY2Fj"
        "aGVfcmVhZCwgc3VtKGNhY2hlX3dyaXRlX3Rva2VucykgYXMgY2FjaGVfd3JpdGUsICIKICAgICAg"
        "ICAgICAgICAgICJzdW0ocmVhc29uaW5nX3Rva2VucykgYXMgcmVhc29uaW5nLCAiCiAgICAgICAg"
        "ICAgICAgICAicm91bmQoc3VtKGNvYWxlc2NlKGVzdGltYXRlZF9jb3N0X3VzZCwgYWN0dWFsX2Nv"
        "c3RfdXNkLCAwKSksIDYpIGFzIGVzdF91c2QgIgogICAgICAgICAgICAgICAgImZyb20gc2Vzc2lv"
        "bl9tb2RlbF91c2FnZSB3aGVyZSBzZXNzaW9uX2lkID0gPyAiCiAgICAgICAgICAgICAgICAiZ3Jv"
        "dXAgYnkgYmlsbGluZ19wcm92aWRlciwgbW9kZWwgIgogICAgICAgICAgICAgICAgIm9yZGVyIGJ5"
        "IChzdW0oaW5wdXRfdG9rZW5zKStzdW0ob3V0cHV0X3Rva2Vucykrc3VtKGNhY2hlX3JlYWRfdG9r"
        "ZW5zKStzdW0oY2FjaGVfd3JpdGVfdG9rZW5zKSkgZGVzYyIsCiAgICAgICAgICAgICAgICAoc2Vz"
        "c2lvbl9pZCwpLAogICAgICAgICAgICApLmZldGNoYWxsKCkKICAgICAgICBdCiAgICAgICAgZm9y"
        "IHJvdyBpbiByb3dzOgogICAgICAgICAgICB0ID0gKHJvdy5nZXQoImlucHV0Iikgb3IgMCkgKyAo"
        "cm93LmdldCgib3V0cHV0Iikgb3IgMCkKICAgICAgICAgICAgY3IgPSByb3cuZ2V0KCJjYWNoZV9y"
        "ZWFkIikgb3IgMAogICAgICAgICAgICByb3dbInRvdGFsIl0gPSB0ICsgY3IgKyAocm93LmdldCgi"
        "Y2FjaGVfd3JpdGUiKSBvciAwKQogICAgICAgICAgICBpZiByb3cuZ2V0KCJlc3RfdXNkIikgaXMg"
        "bm90IE5vbmU6CiAgICAgICAgICAgICAgICByb3dbImVzdF91c2QiXSA9IHJvdW5kKHJvd1siZXN0"
        "X3VzZCJdLCA2KQogICAgICAgIHJldHVybiB7Im9rIjogVHJ1ZSwgInNlc3Npb25faWQiOiBzZXNz"
        "aW9uX2lkLCAibW9kZWxzIjogcm93c30KICAgIGZpbmFsbHk6CiAgICAgICAgY29ubi5jbG9zZSgp"
        "CgoKQHJvdXRlci5nZXQoIi9vdmVydmlldyIpCmFzeW5jIGRlZiBvdmVydmlldygpOgogICAgZGIg"
        "PSBfcmVzb2x2ZV9kYl9wYXRoKCkKICAgIGlmIG5vdCBkYi5leGlzdHMoKToKICAgICAgICByZXR1"
        "cm4gewogICAgICAgICAgICAib2siOiBGYWxzZSwKICAgICAgICAgICAgImVycm9yIjogZiJzdGF0"
        "ZS5kYiBub3QgZm91bmQgYXQge2RifSIsCiAgICAgICAgICAgICJtZXRhIjoge30sCiAgICAgICAg"
        "ICAgICJ0b3RhbHMiOiB7fSwKICAgICAgICAgICAgInBlcl9tb2RlbCI6IFtdLAogICAgICAgICAg"
        "ICAicGVyX3Nlc3Npb24iOiBbXSwKICAgICAgICAgICAgImRhaWx5IjogW10sCiAgICAgICAgfQog"
        "ICAgY29ubiA9IF9jb25uZWN0KGRiKQogICAgY29ubi5yb3dfZmFjdG9yeSA9IHNxbGl0ZTMuUm93"
        "CiAgICB0cnk6CiAgICAgICAgbWV0YSA9IGRpY3QoY29ubi5leGVjdXRlKAogICAgICAgICAgICAi"
        "c2VsZWN0IGNvdW50KCopIGFzIGFwaV9jYWxscywgY291bnQoZGlzdGluY3Qgc2Vzc2lvbl9pZCkg"
        "YXMgc2Vzc2lvbnMsICIKICAgICAgICAgICAgImNvdW50KGRpc3RpbmN0IG1vZGVsKSBhcyBtb2Rl"
        "bHMsICIKICAgICAgICAgICAgIm1pbihmaXJzdF9zZWVuKSBhcyBmaXJzdF9zZWVuLCBtYXgobGFz"
        "dF9zZWVuKSBhcyBsYXN0X3NlZW4gIgogICAgICAgICAgICAiZnJvbSBzZXNzaW9uX21vZGVsX3Vz"
        "YWdlIgogICAgICAgICkuZmV0Y2hvbmUoKSkKCiAgICAgICAgdG90YWxzID0gZGljdChjb25uLmV4"
        "ZWN1dGUoCiAgICAgICAgICAgICJzZWxlY3QgY29hbGVzY2Uoc3VtKGlucHV0X3Rva2VucyksMCkg"
        "YXMgaW5wdXQsICIKICAgICAgICAgICAgImNvYWxlc2NlKHN1bShvdXRwdXRfdG9rZW5zKSwwKSBh"
        "cyBvdXRwdXQsICIKICAgICAgICAgICAgImNvYWxlc2NlKHN1bShjYWNoZV9yZWFkX3Rva2Vucyks"
        "MCkgYXMgY2FjaGVfcmVhZCwgIgogICAgICAgICAgICAiY29hbGVzY2Uoc3VtKGNhY2hlX3dyaXRl"
        "X3Rva2VucyksMCkgYXMgY2FjaGVfd3JpdGUsICIKICAgICAgICAgICAgImNvYWxlc2NlKHN1bShy"
        "ZWFzb25pbmdfdG9rZW5zKSwwKSBhcyByZWFzb25pbmcsICIKICAgICAgICAgICAgImNvYWxlc2Nl"
        "KHN1bShhcGlfY2FsbF9jb3VudCksMCkgYXMgYXBpX2NhbGxzICIKICAgICAgICAgICAgImZyb20g"
        "c2Vzc2lvbl9tb2RlbF91c2FnZSIKICAgICAgICApLmZldGNob25lKCkpCgogICAgICAgICMgRXN0"
        "aW1hdGVkIGNvc3QgYWNyb3NzIHRoZSB3aG9sZSB0YWJsZSAoZXN0aW1hdGVkIHdoZXJlIHByZXNl"
        "bnQsIGVsc2UgYWN0dWFsKS4KICAgICAgICBjb3N0ID0gY29ubi5leGVjdXRlKAogICAgICAgICAg"
        "ICAic2VsZWN0IGNvYWxlc2NlKHN1bShjb2FsZXNjZShlc3RpbWF0ZWRfY29zdF91c2QsIGFjdHVh"
        "bF9jb3N0X3VzZCwgMCkpLDApIGFzIGVzdF91c2QsICIKICAgICAgICAgICAgImNvdW50KCopIGZp"
        "bHRlciAod2hlcmUgZXN0aW1hdGVkX2Nvc3RfdXNkIGlzIG5vdCBudWxsIGFuZCBlc3RpbWF0ZWRf"
        "Y29zdF91c2QgPiAwKSBhcyBlc3Rfcm93cywgIgogICAgICAgICAgICAiY291bnQoKikgZmlsdGVy"
        "ICh3aGVyZSBhY3R1YWxfY29zdF91c2QgaXMgbm90IG51bGwgYW5kIGFjdHVhbF9jb3N0X3VzZCA+"
        "IDApIGFzIGFjdF9yb3dzICIKICAgICAgICAgICAgImZyb20gc2Vzc2lvbl9tb2RlbF91c2FnZSIK"
        "ICAgICAgICApLmZldGNob25lKCkKICAgICAgICBtZXRhWyJlc3Rfcm93cyJdID0gY29zdFsiZXN0"
        "X3Jvd3MiXQogICAgICAgIG1ldGFbImFjdF9yb3dzIl0gPSBjb3N0WyJhY3Rfcm93cyJdCiAgICAg"
        "ICAgbWV0YVsiZXN0X3VzZCJdID0gcm91bmQoX2YoY29zdFsiZXN0X3VzZCJdKSBvciAwLjAsIDYp"
        "CgogICAgICAgIHRpbiA9IHRvdGFsc1siaW5wdXQiXSBvciAwCiAgICAgICAgY2FjaGVfcmVhZCA9"
        "IHRvdGFsc1siY2FjaGVfcmVhZCJdIG9yIDAKICAgICAgICB0b3RhbHNbInRvdGFsIl0gPSB0aW4g"
        "KyAodG90YWxzWyJvdXRwdXQiXSBvciAwKSArIGNhY2hlX3JlYWQgKyAodG90YWxzWyJjYWNoZV93"
        "cml0ZSJdIG9yIDApCiAgICAgICAgdG90YWxzWyJjYWNoZV9zaGFyZV9vZl9pbnB1dCJdID0gcm91"
        "bmQoY2FjaGVfcmVhZCAvIHRpbiwgNCkgaWYgdGluIGVsc2UgTm9uZQogICAgICAgIHRvdGFsc1si"
        "ZXN0X3VzZCJdID0gbWV0YVsiZXN0X3VzZCJdCgogICAgICAgIHBlcl9tb2RlbCA9IFsKICAgICAg"
        "ICAgICAgZGljdChyKQogICAgICAgICAgICBmb3IgciBpbiBjb25uLmV4ZWN1dGUoCiAgICAgICAg"
        "ICAgICAgICAic2VsZWN0IGJpbGxpbmdfcHJvdmlkZXIgYXMgcHJvdmlkZXIsIG1vZGVsLCBjb3Vu"
        "dCgqKSBhcyBjYWxscywgIgogICAgICAgICAgICAgICAgInN1bShpbnB1dF90b2tlbnMpIGFzIGlu"
        "cHV0LCBzdW0ob3V0cHV0X3Rva2VucykgYXMgb3V0cHV0LCAiCiAgICAgICAgICAgICAgICAic3Vt"
        "KGNhY2hlX3JlYWRfdG9rZW5zKSBhcyBjYWNoZV9yZWFkLCBzdW0oY2FjaGVfd3JpdGVfdG9rZW5z"
        "KSBhcyBjYWNoZV93cml0ZSwgIgogICAgICAgICAgICAgICAgInN1bShyZWFzb25pbmdfdG9rZW5z"
        "KSBhcyByZWFzb25pbmcsICIKICAgICAgICAgICAgICAgICJyb3VuZChzdW0oY29hbGVzY2UoZXN0"
        "aW1hdGVkX2Nvc3RfdXNkLCBhY3R1YWxfY29zdF91c2QsIDApKSwgNikgYXMgZXN0X3VzZCAiCiAg"
        "ICAgICAgICAgICAgICAiZnJvbSBzZXNzaW9uX21vZGVsX3VzYWdlIGdyb3VwIGJ5IGJpbGxpbmdf"
        "cHJvdmlkZXIsIG1vZGVsICIKICAgICAgICAgICAgICAgICJvcmRlciBieSAoc3VtKGlucHV0X3Rv"
        "a2Vucykrc3VtKG91dHB1dF90b2tlbnMpK3N1bShjYWNoZV9yZWFkX3Rva2Vucykrc3VtKGNhY2hl"
        "X3dyaXRlX3Rva2VucykpIGRlc2MiCiAgICAgICAgICAgICkuZmV0Y2hhbGwoKQogICAgICAgIF0K"
        "ICAgICAgICBmb3Igcm93IGluIHBlcl9tb2RlbDoKICAgICAgICAgICAgdCA9IChyb3cuZ2V0KCJp"
        "bnB1dCIpIG9yIDApICsgKHJvdy5nZXQoIm91dHB1dCIpIG9yIDApCiAgICAgICAgICAgIGNyID0g"
        "cm93LmdldCgiY2FjaGVfcmVhZCIpIG9yIDAKICAgICAgICAgICAgcm93WyJ0b3RhbCJdID0gdCAr"
        "IGNyICsgKHJvdy5nZXQoImNhY2hlX3dyaXRlIikgb3IgMCkKICAgICAgICAgICAgcm93WyJjYWNo"
        "ZV9zaGFyZV9vZl9pbnB1dCJdID0gcm91bmQoY3IgLyAocm93LmdldCgiaW5wdXQiKSBvciAwKSwg"
        "NCkgaWYgcm93LmdldCgiaW5wdXQiKSBlbHNlIE5vbmUKICAgICAgICAgICAgaWYgcm93LmdldCgi"
        "ZXN0X3VzZCIpIGlzIG5vdCBOb25lOgogICAgICAgICAgICAgICAgcm93WyJlc3RfdXNkIl0gPSBy"
        "b3VuZChyb3dbImVzdF91c2QiXSwgNikKCiAgICAgICAgcGVyX3Nlc3Npb24gPSBbCiAgICAgICAg"
        "ICAgIGRpY3QocikKICAgICAgICAgICAgZm9yIHIgaW4gY29ubi5leGVjdXRlKAogICAgICAgICAg"
        "ICAgICAgInNlbGVjdCB1LnNlc3Npb25faWQsIGNvYWxlc2NlKHMudGl0bGUsIHMuZGlzcGxheV9u"
        "YW1lLCBzdWJzdHIocy5zZXNzaW9uX2tleSwxLDYwKSwgdS5zZXNzaW9uX2lkKSBhcyB0aXRsZSwg"
        "IgogICAgICAgICAgICAgICAgInMuc3RhcnRlZF9hdCwgcy5sYXN0X2FjdGl2aXR5X2F0LCB1Lm1v"
        "ZGVsLCB1LmJpbGxpbmdfcHJvdmlkZXIgYXMgcHJvdmlkZXIsICIKICAgICAgICAgICAgICAgICJz"
        "dW0odS5pbnB1dF90b2tlbnMpIGFzIGlucHV0LCBzdW0odS5vdXRwdXRfdG9rZW5zKSBhcyBvdXRw"
        "dXQsICIKICAgICAgICAgICAgICAgICJzdW0odS5jYWNoZV9yZWFkX3Rva2VucykgYXMgY2FjaGVf"
        "cmVhZCwgc3VtKHUuY2FjaGVfd3JpdGVfdG9rZW5zKSBhcyBjYWNoZV93cml0ZSwgIgogICAgICAg"
        "ICAgICAgICAgInN1bSh1LnJlYXNvbmluZ190b2tlbnMpIGFzIHJlYXNvbmluZywgc3VtKHUuYXBp"
        "X2NhbGxfY291bnQpIGFzIGNhbGxzLCAiCiAgICAgICAgICAgICAgICAicm91bmQoc3VtKGNvYWxl"
        "c2NlKHUuZXN0aW1hdGVkX2Nvc3RfdXNkLCB1LmFjdHVhbF9jb3N0X3VzZCwgMCkpLCA2KSBhcyBl"
        "c3RfdXNkICIKICAgICAgICAgICAgICAgICJmcm9tIHNlc3Npb25fbW9kZWxfdXNhZ2UgdSBsZWZ0"
        "IGpvaW4gc2Vzc2lvbnMgcyBvbiBzLmlkID0gdS5zZXNzaW9uX2lkICIKICAgICAgICAgICAgICAg"
        "ICJncm91cCBieSB1LnNlc3Npb25faWQgb3JkZXIgYnkgKHN1bSh1LmlucHV0X3Rva2Vucykrc3Vt"
        "KHUub3V0cHV0X3Rva2VucykrIgogICAgICAgICAgICAgICAgInN1bSh1LmNhY2hlX3JlYWRfdG9r"
        "ZW5zKStzdW0odS5jYWNoZV93cml0ZV90b2tlbnMpKSBkZXNjIGxpbWl0IDMwIgogICAgICAgICAg"
        "ICApLmZldGNoYWxsKCkKICAgICAgICBdCiAgICAgICAgZm9yIHJvdyBpbiBwZXJfc2Vzc2lvbjoK"
        "ICAgICAgICAgICAgdCA9IChyb3cuZ2V0KCJpbnB1dCIpIG9yIDApICsgKHJvdy5nZXQoIm91dHB1"
        "dCIpIG9yIDApCiAgICAgICAgICAgIGNyID0gcm93LmdldCgiY2FjaGVfcmVhZCIpIG9yIDAKICAg"
        "ICAgICAgICAgcm93WyJ0b3RhbCJdID0gdCArIGNyICsgKHJvdy5nZXQoImNhY2hlX3dyaXRlIikg"
        "b3IgMCkKCiAgICAgICAgIyBEYWlseSB0cmVuZCBvdmVyIHRoZSBsYXN0IE4gY29tcGxldGUtaXNo"
        "IFVUQyBkYXlzLCBidWNrZXRlZCBieSBmaXJzdF9zZWVuLgogICAgICAgIG5fZGF5cyA9IDMwCiAg"
        "ICAgICAgc3RhcnQgPSBfbm93X3V0Y19kYXkoKSAtIChuX2RheXMgLSAxKQogICAgICAgIHJvd3Mg"
        "PSBjb25uLmV4ZWN1dGUoCiAgICAgICAgICAgICJzZWxlY3QgY2FzdChmaXJzdF9zZWVuIC8gODY0"
        "MDAuMCBhcyBpbnQpIGFzIGRheSwgIgogICAgICAgICAgICAic3VtKGlucHV0X3Rva2VucykgYXMg"
        "aW5wdXQsIHN1bShvdXRwdXRfdG9rZW5zKSBhcyBvdXRwdXQsICIKICAgICAgICAgICAgInN1bShj"
        "YWNoZV9yZWFkX3Rva2VucykgYXMgY2FjaGVfcmVhZCwgc3VtKGNhY2hlX3dyaXRlX3Rva2Vucykg"
        "YXMgY2FjaGVfd3JpdGUsICIKICAgICAgICAgICAgInN1bShyZWFzb25pbmdfdG9rZW5zKSBhcyBy"
        "ZWFzb25pbmcsICIKICAgICAgICAgICAgInJvdW5kKHN1bShjb2FsZXNjZShlc3RpbWF0ZWRfY29z"
        "dF91c2QsIGFjdHVhbF9jb3N0X3VzZCwgMCkpLCA2KSBhcyBlc3RfdXNkICIKICAgICAgICAgICAg"
        "ImZyb20gc2Vzc2lvbl9tb2RlbF91c2FnZSBncm91cCBieSBkYXkiCiAgICAgICAgKS5mZXRjaGFs"
        "bCgpCiAgICAgICAgYnlfZGF5ID0ge3JbImRheSJdOiByIGZvciByIGluIHJvd3N9CiAgICAgICAg"
        "ZGFpbHkgPSBbXQogICAgICAgIGZvciBkIGluIHJhbmdlKHN0YXJ0LCBzdGFydCArIG5fZGF5cyk6"
        "CiAgICAgICAgICAgIHIgPSBieV9kYXkuZ2V0KGQpCiAgICAgICAgICAgIGRheV9kYXRlID0gZGF0"
        "ZXRpbWUuZnJvbXRpbWVzdGFtcChkICogX1VUQ19EQVksIHR6PXRpbWV6b25lLnV0Yykuc3RyZnRp"
        "bWUoIiVZLSVtLSVkIikKICAgICAgICAgICAgaWYgciBpcyBOb25lOgogICAgICAgICAgICAgICAg"
        "ZGFpbHkuYXBwZW5kKHsiZGF0ZSI6IGRheV9kYXRlLCAiZGF5IjogZCwgImFjdGl2ZSI6IEZhbHNl"
        "fSkKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIHRvdGFsID0gKHJbImlucHV0"
        "Il0gb3IgMCkgKyAoclsib3V0cHV0Il0gb3IgMCkgKyAoclsiY2FjaGVfcmVhZCJdIG9yIDApICsg"
        "KHJbImNhY2hlX3dyaXRlIl0gb3IgMCkKICAgICAgICAgICAgZGFpbHkuYXBwZW5kKHsKICAgICAg"
        "ICAgICAgICAgICJkYXRlIjogZGF5X2RhdGUsICJkYXkiOiBkLCAiYWN0aXZlIjogVHJ1ZSwgInRv"
        "dGFsIjogdG90YWwsCiAgICAgICAgICAgICAgICAiaW5wdXQiOiByWyJpbnB1dCJdIG9yIDAsICJv"
        "dXRwdXQiOiByWyJvdXRwdXQiXSBvciAwLAogICAgICAgICAgICAgICAgImNhY2hlX3JlYWQiOiBy"
        "WyJjYWNoZV9yZWFkIl0gb3IgMCwgImNhY2hlX3dyaXRlIjogclsiY2FjaGVfd3JpdGUiXSBvciAw"
        "LAogICAgICAgICAgICAgICAgInJlYXNvbmluZyI6IHJbInJlYXNvbmluZyJdIG9yIDAsCiAgICAg"
        "ICAgICAgICAgICAiZXN0X3VzZCI6IHJvdW5kKHJbImVzdF91c2QiXSBvciAwLCA2KSBpZiByWyJl"
        "c3RfdXNkIl0gaXMgbm90IE5vbmUgZWxzZSBOb25lLAogICAgICAgICAgICB9KQoKICAgICAgICBy"
        "ZXR1cm4gewogICAgICAgICAgICAib2siOiBUcnVlLAogICAgICAgICAgICAibWV0YSI6IG1ldGEs"
        "CiAgICAgICAgICAgICJ0b3RhbHMiOiB0b3RhbHMsCiAgICAgICAgICAgICJwZXJfbW9kZWwiOiBw"
        "ZXJfbW9kZWwsCiAgICAgICAgICAgICJwZXJfc2Vzc2lvbiI6IHBlcl9zZXNzaW9uLAogICAgICAg"
        "ICAgICAiZGFpbHkiOiBkYWlseSwKICAgICAgICB9CiAgICBmaW5hbGx5OgogICAgICAgIGNvbm4u"
        "Y2xvc2UoKQo="
    )

B64_plugins_hermes_usage_dashboard_manifest_json = (
        "ewogICJuYW1lIjogImhlcm1lcy11c2FnZSIsCiAgImxhYmVsIjogIlRva2VuIOeUqOmHjyIsCiAg"
        "ImRlc2NyaXB0aW9uIjogIlBlcnNpc3RlbnQgdG9rZW4tdXNhZ2UgYmFja2VuZDogcmVhZHMgSGVy"
        "bWVzJyBvd24gc3RhdGUuZGIgKHNlc3Npb25zICsgc2Vzc2lvbl9tb2RlbF91c2FnZSkgYW5kIHNl"
        "cnZlcyBkc2gtdG9rZW4tdXNhZ2Utc3R5bGUgYWdncmVnYXRpb25zIHRvIHRoZSBkZXNrdG9wIC91"
        "c2FnZSBkYXNoYm9hcmQuIEJhY2tlbmQgb25seSDigJQgbm8gd2ViLWRhc2hib2FyZCB0YWIuIiwK"
        "ICAiaWNvbiI6ICJHcmFwaExpbmUiLAogICJ2ZXJzaW9uIjogIjAuMS4wIiwKICAiYXBpIjogInBs"
        "dWdpbl9hcGkucHkiCn0K"
    )

def candidate_homes():
    out = []
    env = os.environ.get("HERMES_HOME")
    if env:
        out.append(Path(env))
    out.append(Path.home() / ".hermes")
    la = os.environ.get("LOCALAPPDATA")
    if la:
        out.append(Path(la) / "hermes")
    dedup = []
    for h in out:
        if h not in dedup:
            dedup.append(h)
    return dedup

def detect(homes):
    env = os.environ.get("HERMES_HOME")
    if env:
        return Path(env)
    scored = []
    for h in homes:
        if not h.exists():
            continue
        s = 0
        if (h / "config.yaml").exists():
            s += 2
        if (h / "state.db").exists():
            s += 4
        if (h / "desktop-plugins").is_dir():
            s += 4
        if (h / "plugins").is_dir():
            s += 2
        if (h / "desktop-plugins" / "hermes-usage").is_dir():
            s += 9
        scored.append((s, h))
    if not scored:
        return (homes[0] if homes else Path.home() / ".hermes")
    scored.sort(key=lambda x: x[0], reverse=True)
    return scored[0][1]

ARTIFACTS = [
    ("desktop-plugins/hermes-usage/plugin.js", B64_desktop_plugins_hermes_usage_plugin_js),
    ("plugins/hermes-usage/dashboard/plugin_api.py", B64_plugins_hermes_usage_dashboard_plugin_api_py),
    ("plugins/hermes-usage/dashboard/manifest.json", B64_plugins_hermes_usage_dashboard_manifest_json),
]

def write_files(home, bar_only):
    n = 0
    for rel, b64 in ARTIFACTS:
        if bar_only and not rel.startswith("desktop-plugins"):
            continue
        p = home / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(base64.b64decode(b64))
        print("  wrote  %s" % rel)
        n += 1
    return n

def enable_backend(home):
    cfg = home / "config.yaml"
    if not cfg.exists():
        print("  !! 未找到 config.yaml, 跳过后端启用(底部条仍可用; 详情页需要后端)")
        print("     手动启用: hermes config set plugins.enabled \"['hermes-usage']\"")
        return
    try:
        import yaml
    except Exception:
        print("  !! 本机无 PyYAML, 跳过自动启用(不影响底部条)")
        print("     手动启用: hermes config set plugins.enabled \"['hermes-usage']\"")
        return
    try:
        data = yaml.safe_load(cfg.read_text(encoding="utf-8")) or {}
    except Exception as ex:
        print("  !! 读取 config.yaml 失败 (%s), 跳过自动启用" % ex)
        return
    plugins = data.get("plugins")
    if not isinstance(plugins, dict):
        plugins = {}
        data["plugins"] = plugins
    enabled = plugins.get("enabled")
    if not isinstance(enabled, list):
        enabled = []
    if "hermes-usage" not in enabled:
        enabled.append("hermes-usage")
    plugins["enabled"] = enabled
    bak = cfg.with_name(cfg.name + ".bak-hermes-usage")
    if not bak.exists():
        try:
            bak.write_text(cfg.read_text(encoding="utf-8"), encoding="utf-8")
        except Exception:
            pass
    try:
        cfg.write_text(
            yaml.safe_dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False),
            encoding="utf-8",
        )
        print("  已将 'hermes-usage' 加入 plugins.enabled (原配置已备份为 config.yaml.bak-hermes-usage)")
    except Exception as ex:
        print("  !! 写回 config.yaml 失败 (%s)" % ex)
        print("     手动启用: hermes config set plugins.enabled \"['hermes-usage']\"")

def main():
    bar_only = "--bar-only" in sys.argv
    if "-h" in sys.argv or "--help" in sys.argv:
        print(__doc__)
        return 0
    homes = candidate_homes()
    home = detect(homes)
    print("Hermes 数据目录: %s" % home)
    if not home.exists():
        home.mkdir(parents=True, exist_ok=True)
    n = write_files(home, bar_only)
    print("  写入 %d 个文件" % n)
    if not bar_only:
        enable_backend(home)
    print()
    print("完成。请彻底退出 Hermes 桌面端(含托盘)后重开。")
    print("若底部用量条未出现: Ctrl+K -> Reload desktop plugins")
    return 0

if __name__ == "__main__":
    sys.exit(main())
