#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
hermes-usage  单文件安装器 (Token 用量: Hermes 底部实时用量条 + /usage 历史详情页)

在一台已安装 Hermes 的机器上运行即可直接使用:

    方式A(完整版,含历史详情页,推荐):    python install_hermes_usage.py
    方式B(仅底部用量条,免改配置,零依赖): python install_hermes_usage.py --bar-only

自动探测 Hermes 数据目录(HERMES_HOME)并按需写入:
    <home>/desktop-plugins/hermes-usage/plugin.js
    <home>/plugins/hermes-usage/dashboard/{manifest.json,plugin_api.py}
并把插件加入 config.yaml 的 plugins.enabled(会先备份 config.yaml.bak-hermes-usage)。

安装后: 彻底退出 Hermes 桌面端(含托盘)再打开; 若底部条没出现,
按 Ctrl+K 输入 Reload desktop plugins 回车。数据来自 Hermes 自带的
state.db(session_model_usage), 不拦截、不改库。
"""
import base64
import os
import sys
from pathlib import Path

__version__ = "0.3.0"

B64_desktop_plugins_hermes_usage_plugin_js = (
        "LyoqCiAqIGhlcm1lcy11c2FnZSDigJQgdG9rZW4tdXNhZ2UgYmFyIGRvY2tlZCBhdCB0aGUgQk9U"
        "VE9NIG9mIHRoZSBIZXJtZXMgVUkuCiAqCiAqIEJvdHRvbSBwYW5lIChhbHdheXMgdmlzaWJsZSwg"
        "bGlrZSBhIERlZXBTZWVrLUhhcm5lc3MgYm90dG9tIGJhcikgc2hvd2luZyB0aGUKICogRk9DVVNF"
        "RCBzZXNzaW9uJ3MgbGl2ZSB1c2FnZSwgc3RyZWFtZWQgdmlhIGhvc3Quc3RhdGUuZm9jdXNlZFVz"
        "YWdlIChubwogKiBiYWNrZW5kIG5lZWRlZCk6IGlucHV0IC8gb3V0cHV0IC8gY2FjaGUtaGl0JSAv"
        "IHRvdGFsIC8gY2FsbHMgLyBjb3N0LgogKiBDbGljayB0aGUgYmFyIHRvIG9wZW4gdGhlIGZ1bGwg"
        "L3VzYWdlIGRldGFpbCBwYWdlIChyZWFkcyBzdGF0ZS5kYiB2aWEgdGhlCiAqIHNpYmxpbmcgcGx1"
        "Z2luX2FwaS5weSBiYWNrZW5kIGZvciBwZXItbW9kZWwgJiBwZXItc2Vzc2lvbiBoaXN0b3J5KS4K"
        "ICoKICogUGxhaW4gRVNNLCBsb2FkZWQgdW5jb21waWxlZCDigJQgVUkgaXMganN4KCkgY2FsbHMu"
        "IE9ubHkgdGhlc2UgaW1wb3J0cyByZXNvbHZlOgogKiAgIEBoZXJtZXMvcGx1Z2luLXNkaywgcmVh"
        "Y3QsIHJlYWN0L2pzeC1ydW50aW1lCiAqLwoKaW1wb3J0IHsgaG9zdCwgdXNlVmFsdWUsIGhhcHRp"
        "YywgUEFORVNfQVJFQSwgUk9VVEVTX0FSRUEsIFBBTEVUVEVfQVJFQSB9IGZyb20gJ0BoZXJtZXMv"
        "cGx1Z2luLXNkaycKaW1wb3J0IHsganN4LCBqc3hzIH0gZnJvbSAncmVhY3QvanN4LXJ1bnRpbWUn"
        "CmltcG9ydCB7IHVzZUVmZmVjdCwgdXNlU3RhdGUgfSBmcm9tICdyZWFjdCcKCmNvbnN0IElEID0g"
        "J2hlcm1lcy11c2FnZScKY29uc3QgUkVGUkVTSF9NUyA9IDIwMDAwCgovKiAtLS0tLS0tLS0tIG51"
        "bWJlciBmb3JtYXR0aW5nIC0tLS0tLS0tLS0gKi8KZnVuY3Rpb24gZm10KG4pIHsKICBpZiAobiA9"
        "PT0gbnVsbCB8fCBuID09PSB1bmRlZmluZWQgfHwgTnVtYmVyLmlzTmFOKE51bWJlcihuKSkpIHJl"
        "dHVybiAn4oCUJwogIG4gPSBOdW1iZXIobikKICBpZiAobiA8IDApIHJldHVybiAn4oCUJwogIGlm"
        "IChuID49IDFlOSkgcmV0dXJuIChuIC8gMWU5KS50b0ZpeGVkKDIpICsgJ0InCiAgaWYgKG4gPj0g"
        "MWU2KSByZXR1cm4gKG4gLyAxZTYpLnRvRml4ZWQoMikgKyAnTScKICBpZiAobiA+PSAxZTQpIHJl"
        "dHVybiAobiAvIDFlMykudG9GaXhlZCgxKSArICdLJwogIHJldHVybiBNYXRoLnJvdW5kKG4pLnRv"
        "TG9jYWxlU3RyaW5nKCkKfQpmdW5jdGlvbiBmbXRVc2QobikgewogIGlmIChuID09PSBudWxsIHx8"
        "IG4gPT09IHVuZGVmaW5lZCB8fCBuID09PSAwKSByZXR1cm4gJyQwJwogIGlmIChuIDwgMC4wMSkg"
        "cmV0dXJuICckJyArIG4udG9GaXhlZCg0KQogIHJldHVybiAnJCcgKyBuLnRvRml4ZWQoMikKfQpm"
        "dW5jdGlvbiBmbXREYXRlKHNlYykgewogIGlmICghc2VjKSByZXR1cm4gJ+KAlCcKICBjb25zdCBk"
        "ID0gbmV3IERhdGUoc2VjICogMTAwMCkKICBjb25zdCBwID0geCA9PiBTdHJpbmcoeCkucGFkU3Rh"
        "cnQoMiwgJzAnKQogIHJldHVybiBgJHtkLmdldEZ1bGxZZWFyKCl9LSR7cChkLmdldE1vbnRoKCkg"
        "KyAxKX0tJHtwKGQuZ2V0RGF0ZSgpKX0gJHtwKGQuZ2V0SG91cnMoKSl9OiR7cChkLmdldE1pbnV0"
        "ZXMoKSl9YAp9CgovKiAtLS0tLS0tLS0tIGxpdmUgYm90dG9tIGJhciAodGhlIGFsd2F5cy12aXNp"
        "YmxlIG1ldGVyKSAtLS0tLS0tLS0tICovCmZ1bmN0aW9uIE1ldGVyQ2hpcCh7IGxhYmVsLCB2YWx1"
        "ZSwgdGl0bGUsIHN0cm9uZyB9KSB7CiAgcmV0dXJuIGpzeHMoJ3NwYW4nLCB7CiAgICBjbGFzc05h"
        "bWU6ICdpbmxpbmUtZmxleCBpdGVtcy1iYXNlbGluZSBnYXAtMSB3aGl0ZXNwYWNlLW5vd3JhcCcs"
        "CiAgICB0aXRsZTogdGl0bGUsCiAgICBjaGlsZHJlbjogWwogICAgICBqc3goJ3NwYW4nLCB7IGNs"
        "YXNzTmFtZTogJ3RleHQtWzAuNjg3NXJlbV0gdGV4dC0oLS11aS10ZXh0LXF1YXRlcm5hcnkpJywg"
        "Y2hpbGRyZW46IGxhYmVsIH0pLAogICAgICBqc3goJ3NwYW4nLCB7CiAgICAgICAgY2xhc3NOYW1l"
        "OiBzdHJvbmcKICAgICAgICAgID8gJ3RleHQtWzAuODEyNXJlbV0gZm9udC1zZW1pYm9sZCB0YWJ1"
        "bGFyLW51bXMgdGV4dC0oLS11aS1hY2NlbnQpJwogICAgICAgICAgOiAndGV4dC1bMC42ODc1cmVt"
        "XSBmb250LW1lZGl1bSB0YWJ1bGFyLW51bXMgdGV4dC0oLS11aS10ZXh0LXNlY29uZGFyeSknLAog"
        "ICAgICAgIGNoaWxkcmVuOiB2YWx1ZQogICAgICB9KQogICAgXQogIH0pCn0KCmZ1bmN0aW9uIG1v"
        "ZGVsU2hvcnQobmFtZSkgewogIGlmICghbmFtZSkgcmV0dXJuICfigJQnCiAgY29uc3QgcyA9IFN0"
        "cmluZyhuYW1lKQogIGNvbnN0IGkgPSBzLmxhc3RJbmRleE9mKCcvJykKICByZXR1cm4gaSA+PSAw"
        "ID8gcy5zbGljZShpICsgMSkgOiBzCn0KCmZ1bmN0aW9uIEJvdHRvbUJhcih7IGxvYWRNb2RlbHMg"
        "fSkgewogIGNvbnN0IHUgPSB1c2VWYWx1ZShob3N0LnN0YXRlLmZvY3VzZWRVc2FnZSkKICBjb25z"
        "dCBtb2RlbCA9IHVzZVZhbHVlKGhvc3Quc3RhdGUubW9kZWwpCiAgY29uc3Qgc3RvcmVkSWQgPSB1"
        "c2VWYWx1ZShob3N0LnN0YXRlLmZvY3VzZWRTdG9yZWRTZXNzaW9uSWQpCiAgY29uc3QgW21vZGVs"
        "cywgc2V0TW9kZWxzXSA9IHVzZVN0YXRlKG51bGwpCiAgY29uc3Qgb3BlbiA9ICgpID0+IHsgaGFw"
        "dGljKCd0YXAnKTsgaG9zdC5uYXZpZ2F0ZSgnL3VzYWdlJykgfQoKICB1c2VFZmZlY3QoKCkgPT4g"
        "ewogICAgbGV0IGFsaXZlID0gdHJ1ZQogICAgaWYgKCFzdG9yZWRJZCB8fCAhbG9hZE1vZGVscykg"
        "eyBzZXRNb2RlbHMobnVsbCk7IHJldHVybiAoKSA9PiB7IGFsaXZlID0gZmFsc2UgfSB9CiAgICBj"
        "b25zdCBydW4gPSAoKSA9PiB7CiAgICAgIGxvYWRNb2RlbHMoc3RvcmVkSWQpLnRoZW4ocmVzID0+"
        "IHsKICAgICAgICBpZiAoIWFsaXZlKSByZXR1cm4KICAgICAgICBzZXRNb2RlbHMocmVzICYmIHJl"
        "cy5vayAmJiBBcnJheS5pc0FycmF5KHJlcy5tb2RlbHMpID8gcmVzLm1vZGVscyA6IG51bGwpCiAg"
        "ICAgIH0pLmNhdGNoKCgpID0+IHsgaWYgKGFsaXZlKSBzZXRNb2RlbHMobnVsbCkgfSkKICAgIH0K"
        "ICAgIHJ1bigpCiAgICBjb25zdCBpZCA9IHNldEludGVydmFsKHJ1biwgUkVGUkVTSF9NUykKICAg"
        "IHJldHVybiAoKSA9PiB7IGFsaXZlID0gZmFsc2U7IGNsZWFySW50ZXJ2YWwoaWQpIH0KICB9LCBb"
        "c3RvcmVkSWQsIGxvYWRNb2RlbHNdKQoKICBjb25zdCBtdWx0aSA9IG1vZGVscyAmJiBtb2RlbHMu"
        "bGVuZ3RoID4gMQoKICByZXR1cm4ganN4cygnYnV0dG9uJywgewogICAgdHlwZTogJ2J1dHRvbics"
        "CiAgICBvbkNsaWNrOiBvcGVuLAogICAgdGl0bGU6ICfngrnlh7vmiZPlvIAgVG9rZW4g55So6YeP"
        "6K+m5oOF6aG1JywKICAgIGNsYXNzTmFtZTogJ2ZsZXggaC1mdWxsIHctZnVsbCBmbGV4LWNvbCBq"
        "dXN0aWZ5LWNlbnRlciBnYXAtMC41IG92ZXJmbG93LWhpZGRlbiBweC0yIHRleHQtbGVmdCB0ZXh0"
        "LSgtLXVpLXRleHQtc2Vjb25kYXJ5KSBob3Zlcjp0ZXh0LWZvcmVncm91bmQnLAogICAgY2hpbGRy"
        "ZW46IFsKICAgICAgIXUgJiYgIW1vZGVsCiAgICAgICAgPyBqc3goJ3NwYW4nLCB7IGNsYXNzTmFt"
        "ZTogJ3RleHQtWzAuNjg3NXJlbV0gdGV4dC0oLS11aS10ZXh0LXRlcnRpYXJ5KScsIGNoaWxkcmVu"
        "OiAnVG9rZW4g55So6YePIOKAlCDmmoLml6DmtLvliqjkvJror50nIH0pCiAgICAgICAgOiBqc3hz"
        "KCdkaXYnLCB7CiAgICAgICAgICAgIGNsYXNzTmFtZTogJ2ZsZXggaXRlbXMtY2VudGVyIGdhcC0z"
        "IG92ZXJmbG93LWhpZGRlbicsCiAgICAgICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICAgICAg"
        "anN4KCdzcGFuJywgewogICAgICAgICAgICAgICAgY2xhc3NOYW1lOiAnaW5saW5lLWZsZXggbWF4"
        "LXctWzIxMHB4XSBpdGVtcy1jZW50ZXIgZ2FwLTEgdHJ1bmNhdGUgd2hpdGVzcGFjZS1ub3dyYXAg"
        "dGV4dC1bMC42ODc1cmVtXSBmb250LXNlbWlib2xkIHRleHQtKC0tdWktYWNjZW50KScsCiAgICAg"
        "ICAgICAgICAgICB0aXRsZTogJ+W9k+WJjeaooeWeizogJyArIChtb2RlbCB8fCAn4oCUJyksCiAg"
        "ICAgICAgICAgICAgICBjaGlsZHJlbjogbW9kZWwgPyAn5qih5Z6LICcgKyBtb2RlbFNob3J0KG1v"
        "ZGVsKSA6ICfmqKHlnosg4oCUJwogICAgICAgICAgICAgIH0pLAogICAgICAgICAgICAgIHUgPyBq"
        "c3goTWV0ZXJDaGlwLCB7IGxhYmVsOiAn6L6T5YWlJywgdmFsdWU6IGZtdCh1LmlucHV0KSwgdGl0"
        "bGU6ICfovpPlhaUgdG9rZW4nIH0pIDogbnVsbCwKICAgICAgICAgICAgICB1ID8ganN4KE1ldGVy"
        "Q2hpcCwgeyBsYWJlbDogJ+i+k+WHuicsIHZhbHVlOiBmbXQodS5vdXRwdXQpLCB0aXRsZTogJ+i+"
        "k+WHuiB0b2tlbicgfSkgOiBudWxsLAogICAgICAgICAgICAgIHUgJiYgdS5jYWNoZV9oaXRfcGN0"
        "ICE9IG51bGwKICAgICAgICAgICAgICAgID8ganN4KE1ldGVyQ2hpcCwgeyBsYWJlbDogJ+e8k+Wt"
        "mOWRveS4rScsIHZhbHVlOiB1LmNhY2hlX2hpdF9wY3QgKyAnJScsIHRpdGxlOiAn5b2T5YmN5Lya"
        "6K+d5o+Q56S66K+N57yT5a2Y5ZG95Lit546HJyB9KQogICAgICAgICAgICAgICAgOiBudWxsLAog"
        "ICAgICAgICAgICAgIHUgPyBqc3goTWV0ZXJDaGlwLCB7IGxhYmVsOiAn5oC7JywgdmFsdWU6IGZt"
        "dCh1LnRvdGFsKSwgdGl0bGU6ICfmgLsgdG9rZW7vvIjlkKvnvJPlrZjvvIknLCBzdHJvbmc6IHRy"
        "dWUgfSkgOiBudWxsLAogICAgICAgICAgICAgIHUgPyBqc3goTWV0ZXJDaGlwLCB7IGxhYmVsOiAn"
        "6LCD55SoJywgdmFsdWU6IHUuY2FsbHMgPz8gMCwgdGl0bGU6ICdBUEkg6LCD55So5qyh5pWwJyB9"
        "KSA6IG51bGwsCiAgICAgICAgICAgICAgdSAmJiB1LmNvc3RfdXNkICE9IG51bGwgPyBqc3goTWV0"
        "ZXJDaGlwLCB7IGxhYmVsOiAn6LS555SoJywgdmFsdWU6IGZtdFVzZCh1LmNvc3RfdXNkKSwgdGl0"
        "bGU6ICfkvLDnrpfotLnnlKggVVNEJyB9KSA6IG51bGwsCiAgICAgICAgICAgICAgbXVsdGkgPyBq"
        "c3goJ3NwYW4nLCB7IGNsYXNzTmFtZTogJ3doaXRlc3BhY2Utbm93cmFwIHRleHQtWzAuNjg3NXJl"
        "bV0gdGV4dC0oLS11aS10ZXh0LXRlcnRpYXJ5KScsIGNoaWxkcmVuOiAnwrcgJyArIG1vZGVscy5s"
        "ZW5ndGggKyAnIOS4quaooeWeiycgfSkgOiBudWxsCiAgICAgICAgICAgIF0KICAgICAgICAgIH0p"
        "LAogICAgICBtdWx0aQogICAgICAgID8ganN4cygnZGl2JywgewogICAgICAgICAgICBjbGFzc05h"
        "bWU6ICdmbGV4IGl0ZW1zLWNlbnRlciBnYXAtMiBvdmVyZmxvdy1oaWRkZW4nLAogICAgICAgICAg"
        "ICBjaGlsZHJlbjogWwogICAgICAgICAgICAgIGpzeCgnc3BhbicsIHsgY2xhc3NOYW1lOiAnd2hp"
        "dGVzcGFjZS1ub3dyYXAgdGV4dC1bMC42ODc1cmVtXSB0ZXh0LSgtLXVpLXRleHQtcXVhdGVybmFy"
        "eSknLCBjaGlsZHJlbjogJ+acrOS8muivneaMieaooeWeizonIH0pLAogICAgICAgICAgICAgIG1v"
        "ZGVscy5tYXAobW0gPT4ganN4cygnc3BhbicsIHsKICAgICAgICAgICAgICAgIGNsYXNzTmFtZTog"
        "J2lubGluZS1mbGV4IGl0ZW1zLWNlbnRlciBnYXAtMSB3aGl0ZXNwYWNlLW5vd3JhcCByb3VuZGVk"
        "IGJnLSgtLXVpLWJnLWVsZXZhdGVkKSBweC0xLjUgcHktcHggdGV4dC1bMC42ODc1cmVtXScsCiAg"
        "ICAgICAgICAgICAgICB0aXRsZTogKG1tLnByb3ZpZGVyID8gbW0ucHJvdmlkZXIgKyAnIMK3ICcg"
        "OiAnJykgKyAobW0ubW9kZWwgfHwgJycpICsgJyDCtyDmgLsgJyArIChtbS50b3RhbCAhPSBudWxs"
        "ID8gbW0udG90YWwudG9Mb2NhbGVTdHJpbmcoKSA6ICcnKSArICcgwrcgJyArIChtbS5jYWxscyB8"
        "fCAwKSArICcg5qyh6LCD55SoJywKICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAg"
        "ICAgICAgICAgIGpzeCgnc3BhbicsIHsgY2xhc3NOYW1lOiAndGV4dC0oLS11aS10ZXh0LXNlY29u"
        "ZGFyeSknLCBjaGlsZHJlbjogbW9kZWxTaG9ydChtbS5tb2RlbCkgfSksCiAgICAgICAgICAgICAg"
        "ICAgIGpzeCgnc3BhbicsIHsgY2xhc3NOYW1lOiAnZm9udC1tZWRpdW0gdGFidWxhci1udW1zIHRl"
        "eHQtKC0tdWktdGV4dC10ZXJ0aWFyeSknLCBjaGlsZHJlbjogZm10KG1tLnRvdGFsKSB9KQogICAg"
        "ICAgICAgICAgICAgXQogICAgICAgICAgICAgIH0sIChtbS5tb2RlbCB8fCAnJykgKyAnwrcnICsg"
        "U3RyaW5nKG1tLmNhbGxzKSkpCiAgICAgICAgICAgIF0KICAgICAgICAgIH0pCiAgICAgICAgOiBu"
        "dWxsCiAgICBdCiAgfSkKfQoKLyogLS0tLS0tLS0tLSBkZXRhaWwgcGFnZSAoL3VzYWdlKSDigJQg"
        "cmVhZHMgc3RhdGUuZGIgdmlhIGJhY2tlbmQgLS0tLS0tLS0tLSAqLwpmdW5jdGlvbiBTdGF0Q2Fy"
        "ZCh7IGxhYmVsLCB2YWx1ZSwgc3ViLCBhY2NlbnQgfSkgewogIHJldHVybiBqc3hzKCdkaXYnLCB7"
        "CiAgICBjbGFzc05hbWU6ICdmbGV4IGZsZXgtY29sIGdhcC0xIHJvdW5kZWQtbWQgYm9yZGVyIGJv"
        "cmRlci0oLS11aS1zdHJva2Utc2Vjb25kYXJ5KSBiZy0oLS11aS1iZy1lbGV2YXRlZCkgcC0zJywK"
        "ICAgIGNoaWxkcmVuOiBbCiAgICAgIGpzeCgnZGl2JywgeyBjbGFzc05hbWU6ICd0ZXh0LVswLjY4"
        "NzVyZW1dIHVwcGVyY2FzZSB0cmFja2luZy13aWRlIHRleHQtKC0tdWktdGV4dC10ZXJ0aWFyeSkn"
        "LCBjaGlsZHJlbjogbGFiZWwgfSksCiAgICAgIGpzeCgnZGl2JywgewogICAgICAgIGNsYXNzTmFt"
        "ZTogYWNjZW50ID8gJ3RleHQteGwgZm9udC1zZW1pYm9sZCB0ZXh0LSgtLXVpLWFjY2VudCknIDog"
        "J3RleHQteGwgZm9udC1zZW1pYm9sZCB0YWJ1bGFyLW51bXMnLAogICAgICAgIHRpdGxlOiB2YWx1"
        "ZSwKICAgICAgICBjaGlsZHJlbjogdmFsdWUKICAgICAgfSksCiAgICAgIHN1YiA/IGpzeCgnZGl2"
        "JywgeyBjbGFzc05hbWU6ICd0ZXh0LVswLjY4NzVyZW1dIHRleHQtKC0tdWktdGV4dC10ZXJ0aWFy"
        "eSknLCBjaGlsZHJlbjogc3ViIH0pIDogbnVsbAogICAgXQogIH0pCn0KCmZ1bmN0aW9uIFVzYWdl"
        "UGFnZSh7IGxvYWQgfSkgewogIGNvbnN0IFtkYXRhLCBzZXREYXRhXSA9IHVzZVN0YXRlKG51bGwp"
        "CiAgY29uc3QgW2Vycm9yLCBzZXRFcnJvcl0gPSB1c2VTdGF0ZShudWxsKQogIGNvbnN0IFtsb2Fk"
        "aW5nLCBzZXRMb2FkaW5nXSA9IHVzZVN0YXRlKHRydWUpCiAgY29uc3QgW2Fzb2YsIHNldEFzb2Zd"
        "ID0gdXNlU3RhdGUobnVsbCkKICBjb25zdCBbcmVsb2FkS2V5LCBzZXRSZWxvYWRLZXldID0gdXNl"
        "U3RhdGUoMCkKCiAgdXNlRWZmZWN0KCgpID0+IHsKICAgIGxldCBhbGl2ZSA9IHRydWUKICAgIGNv"
        "bnN0IHJ1biA9ICgpID0+IHsKICAgICAgbG9hZCgpLnRoZW4ocmVzID0+IHsKICAgICAgICBpZiAo"
        "IWFsaXZlKSByZXR1cm4KICAgICAgICBzZXREYXRhKHJlcykKICAgICAgICBzZXRFcnJvcihyZXMg"
        "JiYgcmVzLm9rID09PSBmYWxzZSA/IChyZXMuZXJyb3IgfHwgJ3VzYWdlIGJhY2tlbmQgZXJyb3In"
        "KSA6IG51bGwpCiAgICAgICAgc2V0QXNvZihuZXcgRGF0ZSgpKQogICAgICB9KS5jYXRjaChlID0+"
        "IHsKICAgICAgICBpZiAoIWFsaXZlKSByZXR1cm4KICAgICAgICBzZXREYXRhKG51bGwpCiAgICAg"
        "ICAgc2V0RXJyb3IoKGUgJiYgZS5tZXNzYWdlKSB8fCBTdHJpbmcoZSkpCiAgICAgIH0pLmZpbmFs"
        "bHkoKCkgPT4geyBpZiAoYWxpdmUpIHNldExvYWRpbmcoZmFsc2UpIH0pCiAgICB9CiAgICBydW4o"
        "KQogICAgY29uc3QgaWQgPSBzZXRJbnRlcnZhbChydW4sIFJFRlJFU0hfTVMpCiAgICByZXR1cm4g"
        "KCkgPT4geyBhbGl2ZSA9IGZhbHNlOyBjbGVhckludGVydmFsKGlkKSB9CiAgfSwgW2xvYWQsIHJl"
        "bG9hZEtleV0pCgogIGlmIChsb2FkaW5nICYmICFkYXRhICYmICFlcnJvcikgewogICAgcmV0dXJu"
        "IGpzeCgnZGl2JywgeyBjbGFzc05hbWU6ICdmbGV4IGgtZnVsbCBpdGVtcy1jZW50ZXIganVzdGlm"
        "eS1jZW50ZXIgcC04IHRleHQtc20gdGV4dC0oLS11aS10ZXh0LXRlcnRpYXJ5KScsIGNoaWxkcmVu"
        "OiAn5Yqg6L2955So6YeP5pWw5o2u4oCmJyB9KQogIH0KICBpZiAoZXJyb3IpIHsKICAgIHJldHVy"
        "biBqc3hzKCdkaXYnLCB7CiAgICAgIGNsYXNzTmFtZTogJ2ZsZXggaC1mdWxsIGZsZXgtY29sIGl0"
        "ZW1zLXN0YXJ0IGp1c3RpZnktY2VudGVyIGdhcC0zIHAtOCcsCiAgICAgIGNoaWxkcmVuOiBbCiAg"
        "ICAgICAganN4KCdkaXYnLCB7IGNsYXNzTmFtZTogJ3RleHQtc20gZm9udC1tZWRpdW0nLCBjaGls"
        "ZHJlbjogJ+aXoOazleivu+WPlueUqOmHj+WQjuerrycgfSksCiAgICAgICAganN4KCdwcmUnLCB7"
        "IGNsYXNzTmFtZTogJ21heC13LWZ1bGwgd2hpdGVzcGFjZS1wcmUtd3JhcCByb3VuZGVkLW1kIGJv"
        "cmRlciBib3JkZXItKC0tdWktc3Ryb2tlLXNlY29uZGFyeSkgYmctKC0tdWktYmctZWxldmF0ZWQp"
        "IHAtMyB0ZXh0LXhzIHRleHQtKC0tdWktdGV4dC1zZWNvbmRhcnkpJywgY2hpbGRyZW46IGVycm9y"
        "IH0pLAogICAgICAgIGpzeCgnZGl2JywgeyBjbGFzc05hbWU6ICd0ZXh0LXhzIHRleHQtKC0tdWkt"
        "dGV4dC10ZXJ0aWFyeSknLCBjaGlsZHJlbjogJ+WQjuerr+mcgOWKoOWFpSBwbHVnaW5zLmVuYWJs"
        "ZWQg55m95ZCN5Y2V5bm25ZyoIGdhdGV3YXkg6YeN5ZCv5ZCO5oyC6L2944CC5bqV6YOo5p2hKOWu"
        "nuaXtinkuI3kvp3otZblroPvvIzmnKzpobUo5Y6G5Y+yKeS+nei1luWug+OAgicgfSksCiAgICAg"
        "ICAganN4KCdidXR0b24nLCB7CiAgICAgICAgICB0eXBlOiAnYnV0dG9uJywKICAgICAgICAgIGNs"
        "YXNzTmFtZTogJ3JvdW5kZWQtbWQgYmctKC0tdWktYWNjZW50KSBweC0zIHB5LTEuNSB0ZXh0LXNt"
        "IGhvdmVyOm9wYWNpdHktOTAnLAogICAgICAgICAgb25DbGljazogKCkgPT4geyBzZXRSZWxvYWRL"
        "ZXkoayA9PiBrICsgMSk7IHNldExvYWRpbmcodHJ1ZSkgfSwKICAgICAgICAgIGNoaWxkcmVuOiAn"
        "6YeN6K+VJwogICAgICAgIH0pCiAgICAgIF0KICAgIH0pCiAgfQoKICBjb25zdCB0ID0gKGRhdGEg"
        "JiYgZGF0YS50b3RhbHMpIHx8IHt9CiAgY29uc3QgbWV0YSA9IChkYXRhICYmIGRhdGEubWV0YSkg"
        "fHwge30KICBjb25zdCBwZXJNb2RlbCA9IChkYXRhICYmIGRhdGEucGVyX21vZGVsKSB8fCBbXQog"
        "IGNvbnN0IHBlclNlc3Npb24gPSAoZGF0YSAmJiBkYXRhLnBlcl9zZXNzaW9uKSB8fCBbXQogIGNv"
        "bnN0IGRhaWx5ID0gKChkYXRhICYmIGRhdGEuZGFpbHkpIHx8IFtdKS5maWx0ZXIoZCA9PiBkLmFj"
        "dGl2ZSkKICBjb25zdCBjYWNoZVJhdGlvID0gdC5jYWNoZV9zaGFyZV9vZl9pbnB1dAoKICByZXR1"
        "cm4ganN4cygnZGl2JywgewogICAgY2xhc3NOYW1lOiAnZmxleCBoLWZ1bGwgZmxleC1jb2wgZ2Fw"
        "LTQgb3ZlcmZsb3cteS1hdXRvIHAtNCcsCiAgICBjaGlsZHJlbjogWwogICAgICBqc3hzKCdkaXYn"
        "LCB7CiAgICAgICAgY2xhc3NOYW1lOiAnZmxleCBmbGV4LXdyYXAgaXRlbXMtY2VudGVyIGdhcC0z"
        "JywKICAgICAgICBjaGlsZHJlbjogWwogICAgICAgICAganN4KCdkaXYnLCB7IGNsYXNzTmFtZTog"
        "J3RleHQtYmFzZSBmb250LXNlbWlib2xkJywgY2hpbGRyZW46ICdUb2tlbiDnlKjph48nIH0pLAog"
        "ICAgICAgICAganN4KCdzcGFuJywgeyBjbGFzc05hbWU6ICdyb3VuZGVkIGJnLSgtLXVpLWJnLWVs"
        "ZXZhdGVkKSBweC0xLjUgcHktMC41IHRleHQtWzAuNjg3NXJlbV0gdGV4dC0oLS11aS10ZXh0LXNl"
        "Y29uZGFyeSknLAogICAgICAgICAgICBjaGlsZHJlbjogYCR7bWV0YS5tb2RlbHMgfHwgMH0gbW9k"
        "ZWxzIMK3ICR7bWV0YS5zZXNzaW9ucyB8fCAwfSBzZXNzaW9ucyDCtyAke21ldGEuYXBpX2NhbGxz"
        "IHx8IDB9IGNhbGxzYCB9KSwKICAgICAgICAgIGpzeCgnc3BhbicsIHsgY2xhc3NOYW1lOiAndGV4"
        "dC1bMC42ODc1cmVtXSB0ZXh0LSgtLXVpLXRleHQtdGVydGlhcnkpJywKICAgICAgICAgICAgY2hp"
        "bGRyZW46IGFzb2YgPyAn5pu05paw5LqOICcgKyBmbXREYXRlKGFzb2YuZ2V0VGltZSgpIC8gMTAw"
        "MCkgOiAnJyB9KSwKICAgICAgICAgIGpzeCgnYnV0dG9uJywgewogICAgICAgICAgICB0eXBlOiAn"
        "YnV0dG9uJywKICAgICAgICAgICAgY2xhc3NOYW1lOiAnbWwtYXV0byByb3VuZGVkLW1kIGJvcmRl"
        "ciBib3JkZXItKC0tdWktc3Ryb2tlLXNlY29uZGFyeSkgcHgtMiBweS0xIHRleHQteHMgaG92ZXI6"
        "YmctKC0tY2hyb21lLWFjdGlvbi1ob3ZlciknLAogICAgICAgICAgICBvbkNsaWNrOiAoKSA9PiB7"
        "IHNldFJlbG9hZEtleShrID0+IGsgKyAxKTsgc2V0TG9hZGluZyh0cnVlKSB9LAogICAgICAgICAg"
        "ICBjaGlsZHJlbjogJ+WIt+aWsCcKICAgICAgICAgIH0pCiAgICAgICAgXQogICAgICB9KSwKICAg"
        "ICAganN4cygnZGl2JywgewogICAgICAgIGNsYXNzTmFtZTogJ2dyaWQgZ3JpZC1jb2xzLTIgZ2Fw"
        "LTIgbWQ6Z3JpZC1jb2xzLTQnLAogICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICBqc3goU3Rh"
        "dENhcmQsIHsgbGFiZWw6ICfmgLsgVG9rZW4nLCB2YWx1ZTogZm10KHQudG90YWwpLCBzdWI6IFN0"
        "cmluZyh0LnRvdGFsID8/ICcnKSwgYWNjZW50OiB0cnVlIH0pLAogICAgICAgICAganN4KFN0YXRD"
        "YXJkLCB7IGxhYmVsOiAn6L6T5YWlJywgdmFsdWU6IGZtdCh0LmlucHV0KSwgc3ViOiBTdHJpbmco"
        "dC5pbnB1dCA/PyAnJykgfSksCiAgICAgICAgICBqc3goU3RhdENhcmQsIHsgbGFiZWw6ICfovpPl"
        "h7onLCB2YWx1ZTogZm10KHQub3V0cHV0KSwgc3ViOiBTdHJpbmcodC5vdXRwdXQgPz8gJycpIH0p"
        "LAogICAgICAgICAganN4KFN0YXRDYXJkLCB7IGxhYmVsOiAn57yT5a2Y6K+75Y+WJywgdmFsdWU6"
        "IGZtdCh0LmNhY2hlX3JlYWQpLCBzdWI6IFN0cmluZyh0LmNhY2hlX3JlYWQgPz8gJycpIH0pLAog"
        "ICAgICAgICAganN4KFN0YXRDYXJkLCB7IGxhYmVsOiAn5o6o55CGJywgdmFsdWU6IGZtdCh0LnJl"
        "YXNvbmluZyksIHN1YjogU3RyaW5nKHQucmVhc29uaW5nID8/ICcnKSB9KSwKICAgICAgICAgIGpz"
        "eChTdGF0Q2FyZCwgeyBsYWJlbDogJ+S8sOeul+i0ueeUqCcsIHZhbHVlOiBmbXRVc2QodC5lc3Rf"
        "dXNkKSwgc3ViOiBgJHttZXRhLmVzdF9yb3dzIHx8IDB9IOi3r+eUseiuoeWFpei0ueeOh2AsIGFj"
        "Y2VudDogdHJ1ZSB9KSwKICAgICAgICAgIGpzeChTdGF0Q2FyZCwgeyBsYWJlbDogJ0FQSSDosIPn"
        "lKgnLCB2YWx1ZTogZm10KHQuYXBpX2NhbGxzKSwgc3ViOiAnJyB9KSwKICAgICAgICAgIGpzeChT"
        "dGF0Q2FyZCwgeyBsYWJlbDogJ+e8k+WtmCDDtyDovpPlhaUnLCB2YWx1ZTogY2FjaGVSYXRpbyA9"
        "PSBudWxsID8gJ+KAlCcgOiBjYWNoZVJhdGlvLnRvRml4ZWQoMSkgKyAneCcsCiAgICAgICAgICAg"
        "IHN1YjogY2FjaGVSYXRpbyA9PSBudWxsID8gJ+aXoOaVsOaNricgOiAn6K+75Y+W5pS+5aSn5YCN"
        "5pWw77yI6Z2e5ZG95Lit546H77yJJyB9KQogICAgICAgIF0KICAgICAgfSksCiAgICAgIGpzeHMo"
        "J2RpdicsIHsKICAgICAgICBjbGFzc05hbWU6ICdyb3VuZGVkLW1kIGJvcmRlciBib3JkZXItKC0t"
        "dWktc3Ryb2tlLXNlY29uZGFyeSkgYmctKC0tdWktYmctZWxldmF0ZWQpIHAtMycsCiAgICAgICAg"
        "Y2hpbGRyZW46IFsKICAgICAgICAgIGpzeHMoJ2RpdicsIHsgY2xhc3NOYW1lOiAnbWItMiBmbGV4"
        "IGl0ZW1zLWJhc2VsaW5lIGdhcC0yJywKICAgICAgICAgICAgY2hpbGRyZW46IFsganN4KCdkaXYn"
        "LCB7IGNsYXNzTmFtZTogJ3RleHQtc20gZm9udC1tZWRpdW0nLCBjaGlsZHJlbjogJ+i/kSAzMCDl"
        "pKnotovlir8nIH0pLAogICAgICAgICAgICAgIGpzeCgnc3BhbicsIHsgY2xhc3NOYW1lOiAndGV4"
        "dC1bMC42ODc1cmVtXSB0ZXh0LSgtLXVpLXRleHQtdGVydGlhcnkpJywgY2hpbGRyZW46IGAke2Rh"
        "aWx5Lmxlbmd0aH0g5Liq5pyJ6YeP5pelYCB9KSBdIH0pLAogICAgICAgICAgZGFpbHkubGVuZ3Ro"
        "ID09PSAwCiAgICAgICAgICAgID8ganN4KCdkaXYnLCB7IGNsYXNzTmFtZTogJ3B5LTQgdGV4dC1j"
        "ZW50ZXIgdGV4dC1bMC44MTI1cmVtXSB0ZXh0LSgtLXVpLXRleHQtdGVydGlhcnkpJywgY2hpbGRy"
        "ZW46ICfov5EgMzAg5aSp5rKh5pyJ55So6YeP6K6w5b2VJyB9KQogICAgICAgICAgICA6IGpzeHMo"
        "J2RpdicsIHsKICAgICAgICAgICAgICAgIGNsYXNzTmFtZTogJ2ZsZXggZmxleC1jb2wgZ2FwLTEn"
        "LAogICAgICAgICAgICAgICAgY2hpbGRyZW46IGRhaWx5LnNsaWNlKC0xNCkubWFwKGQgPT4gewog"
        "ICAgICAgICAgICAgICAgICBjb25zdCBteCA9IE1hdGgubWF4KC4uLmRhaWx5Lm1hcCh4ID0+IHgu"
        "dG90YWwgfHwgMCksIDEpCiAgICAgICAgICAgICAgICAgIHJldHVybiBqc3hzKCdkaXYnLCB7CiAg"
        "ICAgICAgICAgICAgICAgICAgY2xhc3NOYW1lOiAnZmxleCBpdGVtcy1jZW50ZXIgZ2FwLTInLAog"
        "ICAgICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBbCiAgICAgICAgICAgICAgICAgICAgICBqc3go"
        "J3NwYW4nLCB7IGNsYXNzTmFtZTogJ3ctMTYgc2hyaW5rLTAgdGV4dC1bMC42ODc1cmVtXSB0YWJ1"
        "bGFyLW51bXMgdGV4dC0oLS11aS10ZXh0LXRlcnRpYXJ5KScsIGNoaWxkcmVuOiBkLmRhdGUuc2xp"
        "Y2UoNSkgfSksCiAgICAgICAgICAgICAgICAgICAgICBqc3goJ2RpdicsIHsgY2xhc3NOYW1lOiAn"
        "ZmxleCBmbGV4LTEgZ2FwLTAuNScsCiAgICAgICAgICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBb"
        "CiAgICAgICAgICAgICAgICAgICAgICAgICAganN4KCdkaXYnLCB7IGNsYXNzTmFtZTogJ2gtMiBy"
        "b3VuZGVkLXNtIGJnLSgtLXVpLWFjY2VudCkgb3BhY2l0eS02MCcsIHN0eWxlOiB7IHdpZHRoOiBN"
        "YXRoLm1heCgoZC5jYWNoZV9yZWFkIHx8IDApIC8gbXgsIDAuMDA0KSAqIDEwMCArICclJyB9IH0p"
        "LAogICAgICAgICAgICAgICAgICAgICAgICAgIGpzeCgnZGl2JywgeyBjbGFzc05hbWU6ICdoLTIg"
        "cm91bmRlZC1zbSBiZy0oLS11aS1hY2NlbnQpJywgc3R5bGU6IHsgd2lkdGg6IE1hdGgubWF4KChk"
        "Lm91dHB1dCB8fCAwKSAvIG14LCAwLjAwNCkgKiAxMDAgKyAnJScgfSB9KQogICAgICAgICAgICAg"
        "ICAgICAgICAgICBdIH0pLAogICAgICAgICAgICAgICAgICAgICAganN4KCdzcGFuJywgeyBjbGFz"
        "c05hbWU6ICd3LTE0IHNocmluay0wIHRleHQtcmlnaHQgdGV4dC1bMC42ODc1cmVtXSB0YWJ1bGFy"
        "LW51bXMgdGV4dC0oLS11aS10ZXh0LXNlY29uZGFyeSknLCB0aXRsZTogJ3RvdGFsICcgKyAoZC50"
        "b3RhbCA/PyAwKSwgY2hpbGRyZW46IGZtdChkLnRvdGFsKSB9KQogICAgICAgICAgICAgICAgICAg"
        "IF0KICAgICAgICAgICAgICAgICAgfSwgZC5kYXRlKQogICAgICAgICAgICAgICAgfSkKICAgICAg"
        "ICAgICAgICB9KQogICAgICAgIF0KICAgICAgfSksCiAgICAgIGpzeHMoJ2RpdicsIHsKICAgICAg"
        "ICBjbGFzc05hbWU6ICdyb3VuZGVkLW1kIGJvcmRlciBib3JkZXItKC0tdWktc3Ryb2tlLXNlY29u"
        "ZGFyeSkgYmctKC0tdWktYmctZWxldmF0ZWQpIHAtMycsCiAgICAgICAgY2hpbGRyZW46IFsKICAg"
        "ICAgICAgIGpzeCgnZGl2JywgeyBjbGFzc05hbWU6ICdtYi0yIHRleHQtc20gZm9udC1tZWRpdW0n"
        "LCBjaGlsZHJlbjogJ+aMieaooeWeiycgfSksCiAgICAgICAgICBwZXJNb2RlbC5sZW5ndGggPT09"
        "IDAKICAgICAgICAgICAgPyBqc3goJ2RpdicsIHsgY2xhc3NOYW1lOiAncHktMyB0ZXh0LWNlbnRl"
        "ciB0ZXh0LVswLjgxMjVyZW1dIHRleHQtKC0tdWktdGV4dC10ZXJ0aWFyeSknLCBjaGlsZHJlbjog"
        "J+aaguaXoOaVsOaNricgfSkKICAgICAgICAgICAgOiBqc3goJ3RhYmxlJywgewogICAgICAgICAg"
        "ICAgICAgY2xhc3NOYW1lOiAndy1mdWxsIGJvcmRlci1jb2xsYXBzZSB0ZXh0LVswLjgxMjVyZW1d"
        "JywKICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBqc3hzKCd0Ym9keScsIHsKICAgICAgICAgICAg"
        "ICAgICAgY2hpbGRyZW46IHBlck1vZGVsLm1hcCgobSwgaSkgPT4ganN4cygndHInLCB7CiAgICAg"
        "ICAgICAgICAgICAgICAgY2xhc3NOYW1lOiAnYm9yZGVyLWIgYm9yZGVyLSgtLXVpLXN0cm9rZS1z"
        "ZWNvbmRhcnkpIGxhc3Q6Ym9yZGVyLTAnLAogICAgICAgICAgICAgICAgICAgIGNoaWxkcmVuOiBb"
        "CiAgICAgICAgICAgICAgICAgICAgICBqc3goJ3RkJywgeyBjbGFzc05hbWU6ICdweS0xLjUgcHIt"
        "MicsIGNoaWxkcmVuOiBqc3hzKCdkaXYnLCB7IGNsYXNzTmFtZTogJ2ZsZXggZmxleC1jb2wnLAog"
        "ICAgICAgICAgICAgICAgICAgICAgICBjaGlsZHJlbjogWwogICAgICAgICAgICAgICAgICAgICAg"
        "ICAgIGpzeCgnc3BhbicsIHsgY2xhc3NOYW1lOiAnZm9udC1tZWRpdW0nLCBjaGlsZHJlbjogbS5t"
        "b2RlbCB8fCAn4oCUJyB9KSwKICAgICAgICAgICAgICAgICAgICAgICAgICBtLnByb3ZpZGVyID8g"
        "anN4KCdzcGFuJywgeyBjbGFzc05hbWU6ICd0ZXh0LVswLjY4NzVyZW1dIHRleHQtKC0tdWktdGV4"
        "dC10ZXJ0aWFyeSknLCBjaGlsZHJlbjogbS5wcm92aWRlciB9KSA6IG51bGwKICAgICAgICAgICAg"
        "ICAgICAgICAgICAgXSB9KSB9KSwKICAgICAgICAgICAgICAgICAgICAgIHRjKG0uY2FsbHMsICfo"
        "sIPnlKgnKSwKICAgICAgICAgICAgICAgICAgICAgIHRjKG0uaW5wdXQsICfovpPlhaUnKSwKICAg"
        "ICAgICAgICAgICAgICAgICAgIHRjKG0ub3V0cHV0LCAn6L6T5Ye6JyksCiAgICAgICAgICAgICAg"
        "ICAgICAgICB0YyhtLmNhY2hlX3JlYWQsICfnvJPlrZgnKSwKICAgICAgICAgICAgICAgICAgICAg"
        "IHRjKG0ucmVhc29uaW5nLCAn5o6o55CGJyksCiAgICAgICAgICAgICAgICAgICAgICB0YyhtLmVz"
        "dF91c2QgPT0gbnVsbCA/IG51bGwgOiBmbXRVc2QobS5lc3RfdXNkKSwgJ+i0ueeUqCcpCiAgICAg"
        "ICAgICAgICAgICAgICAgXQogICAgICAgICAgICAgICAgICB9LCAobS5wcm92aWRlciB8fCAnJykg"
        "KyAnwrcnICsgKG0ubW9kZWwgfHwgJycpICsgJ8K3JyArIGkpKQogICAgICAgICAgICAgICAgfSkK"
        "ICAgICAgICAgICAgICB9KQogICAgICAgIF0KICAgICAgfSksCiAgICAgIGpzeHMoJ2RpdicsIHsK"
        "ICAgICAgICBjbGFzc05hbWU6ICdyb3VuZGVkLW1kIGJvcmRlciBib3JkZXItKC0tdWktc3Ryb2tl"
        "LXNlY29uZGFyeSkgYmctKC0tdWktYmctZWxldmF0ZWQpIHAtMycsCiAgICAgICAgY2hpbGRyZW46"
        "IFsKICAgICAgICAgIGpzeCgnZGl2JywgeyBjbGFzc05hbWU6ICdtYi0yIHRleHQtc20gZm9udC1t"
        "ZWRpdW0nLCBjaGlsZHJlbjogJ+aMieS8muivne+8iFRvcCAzMO+8iScgfSksCiAgICAgICAgICBw"
        "ZXJTZXNzaW9uLmxlbmd0aCA9PT0gMAogICAgICAgICAgICA/IGpzeCgnZGl2JywgeyBjbGFzc05h"
        "bWU6ICdweS0zIHRleHQtY2VudGVyIHRleHQtWzAuODEyNXJlbV0gdGV4dC0oLS11aS10ZXh0LXRl"
        "cnRpYXJ5KScsIGNoaWxkcmVuOiAn5pqC5peg5pWw5o2uJyB9KQogICAgICAgICAgICA6IGpzeCgn"
        "dGFibGUnLCB7CiAgICAgICAgICAgICAgICBjbGFzc05hbWU6ICd3LWZ1bGwgYm9yZGVyLWNvbGxh"
        "cHNlIHRleHQtWzAuODEyNXJlbV0nLAogICAgICAgICAgICAgICAgY2hpbGRyZW46IGpzeHMoJ3Ri"
        "b2R5JywgewogICAgICAgICAgICAgICAgICBjaGlsZHJlbjogcGVyU2Vzc2lvbi5tYXAoKHMsIGkp"
        "ID0+IGpzeHMoJ3RyJywgewogICAgICAgICAgICAgICAgICAgIGNsYXNzTmFtZTogJ2JvcmRlci1i"
        "IGJvcmRlci0oLS11aS1zdHJva2Utc2Vjb25kYXJ5KSBsYXN0OmJvcmRlci0wJywKICAgICAgICAg"
        "ICAgICAgICAgICBjaGlsZHJlbjogWwogICAgICAgICAgICAgICAgICAgICAganN4KCd0ZCcsIHsg"
        "Y2xhc3NOYW1lOiAnbWF4LXctWzI0MHB4XSBweS0xLjUgcHItMicsIGNoaWxkcmVuOiBqc3hzKCdk"
        "aXYnLCB7IGNsYXNzTmFtZTogJ2ZsZXggZmxleC1jb2wnLAogICAgICAgICAgICAgICAgICAgICAg"
        "ICBjaGlsZHJlbjogWwogICAgICAgICAgICAgICAgICAgICAgICAgIGpzeCgnc3BhbicsIHsgY2xh"
        "c3NOYW1lOiAndHJ1bmNhdGUgZm9udC1tZWRpdW0nLCB0aXRsZTogcy50aXRsZSB8fCBzLnNlc3Np"
        "b25faWQsIGNoaWxkcmVuOiBzLnRpdGxlIHx8IHMuc2Vzc2lvbl9pZCB9KSwKICAgICAgICAgICAg"
        "ICAgICAgICAgICAgICBqc3goJ3NwYW4nLCB7IGNsYXNzTmFtZTogJ3RleHQtWzAuNjg3NXJlbV0g"
        "dGV4dC0oLS11aS10ZXh0LXRlcnRpYXJ5KScsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBj"
        "aGlsZHJlbjogKHMubW9kZWwgfHwgJycpICsgKHMucHJvdmlkZXIgPyAnIMK3ICcgKyBzLnByb3Zp"
        "ZGVyIDogJycpICsgJyDCtyAnICsgZm10RGF0ZShzLmxhc3RfYWN0aXZpdHlfYXQgfHwgcy5zdGFy"
        "dGVkX2F0KSB9KQogICAgICAgICAgICAgICAgICAgICAgICBdIH0pIH0pLAogICAgICAgICAgICAg"
        "ICAgICAgICAgdGMocy5jYWxscywgJ+iwg+eUqCcpLAogICAgICAgICAgICAgICAgICAgICAgdGMo"
        "cy50b3RhbCwgJ+aAuycpLAogICAgICAgICAgICAgICAgICAgICAgdGMocy5pbnB1dCwgJ+i+k+WF"
        "pScpLAogICAgICAgICAgICAgICAgICAgICAgdGMocy5vdXRwdXQsICfovpPlh7onKSwKICAgICAg"
        "ICAgICAgICAgICAgICAgIHRjKHMuY2FjaGVfcmVhZCwgJ+e8k+WtmCcpLAogICAgICAgICAgICAg"
        "ICAgICAgICAgdGMocy5lc3RfdXNkID09IG51bGwgPyBudWxsIDogZm10VXNkKHMuZXN0X3VzZCks"
        "ICfotLnnlKgnKQogICAgICAgICAgICAgICAgICAgIF0KICAgICAgICAgICAgICAgICAgfSwgKHMu"
        "c2Vzc2lvbl9pZCB8fCAncycpICsgJ8K3JyArIGkpKQogICAgICAgICAgICAgICAgfSkKICAgICAg"
        "ICAgICAgICB9KQogICAgICAgIF0KICAgICAgfSkKICAgIF0KICB9KQp9CgpmdW5jdGlvbiB0Yyh2"
        "LCBsYWJlbCkgewogIHJldHVybiBqc3goJ3RkJywgewogICAgY2xhc3NOYW1lOiAncHktMS41IHB4"
        "LTEgdGV4dC1yaWdodCB0YWJ1bGFyLW51bXMgdGV4dC0oLS11aS10ZXh0LXNlY29uZGFyeSknLAog"
        "ICAgdGl0bGU6IGxhYmVsLAogICAgY2hpbGRyZW46IHYgPT0gbnVsbCA/ICfigJQnIDogdgogIH0p"
        "Cn0KCi8qIC0tLS0tLS0tLS0gcGx1Z2luIGV4cG9ydCAtLS0tLS0tLS0tICovCmV4cG9ydCBkZWZh"
        "dWx0IHsKICBpZDogSUQsCiAgbmFtZTogJ1Rva2VuIOeUqOmHjycsCiAgcmVnaXN0ZXIoY3R4KSB7"
        "CiAgICBjb25zdCBsb2FkID0gKCkgPT4gY3R4LnJlc3QoJy9vdmVydmlldycpCiAgICBjb25zdCBs"
        "b2FkTW9kZWxzID0gc2lkID0+IGN0eC5yZXN0KCcvc2Vzc2lvbl9tb2RlbHM/c2Vzc2lvbl9pZD0n"
        "ICsgZW5jb2RlVVJJQ29tcG9uZW50KFN0cmluZyhzaWQgfHwgJycpKSkKCiAgICAvLyBBbHdheXMt"
        "dmlzaWJsZSBib3R0b20gbWV0ZXIgKGF1dG8tZG9ja2VkIGJlbG93IHRoZSB3b3Jrc3BhY2UgcGFu"
        "ZSkuCiAgICBjdHgucmVnaXN0ZXIoewogICAgICBpZDogJ3BhbmUnLAogICAgICBhcmVhOiBQQU5F"
        "U19BUkVBLAogICAgICB0aXRsZTogJ1Rva2VuIOeUqOmHjycsCiAgICAgIGRhdGE6IHsgcGxhY2Vt"
        "ZW50OiAnYm90dG9tJywgZG9jazogeyBwYW5lOiAnd29ya3NwYWNlJywgcG9zOiAnYm90dG9tJyB9"
        "LCBoZWlnaHQ6ICc1NnB4JyB9LAogICAgICByZW5kZXI6ICgpID0+IGpzeChCb3R0b21CYXIsIHsg"
        "bG9hZE1vZGVscyB9KQogICAgfSkKCiAgICAvLyBEZXRhaWwgcGFnZSAoY2xpY2tpbmcgdGhlIGJh"
        "ciBvcGVucyBpdCkuCiAgICBjdHgucmVnaXN0ZXIoewogICAgICBpZDogJ3BhZ2UnLAogICAgICBh"
        "cmVhOiBST1VURVNfQVJFQSwKICAgICAgZGF0YTogeyBwYXRoOiAnL3VzYWdlJyB9LAogICAgICBy"
        "ZW5kZXI6ICgpID0+IGpzeChVc2FnZVBhZ2UsIHsgbG9hZCB9KQogICAgfSkKCiAgICBjdHgucmVn"
        "aXN0ZXIoewogICAgICBpZDogJ29wZW4nLAogICAgICBhcmVhOiBQQUxFVFRFX0FSRUEsCiAgICAg"
        "IGRhdGE6IHsKICAgICAgICBpZDogJ2hlcm1lcy11c2FnZS5vcGVuJywKICAgICAgICBsYWJlbDog"
        "J+aJk+W8gCBUb2tlbiDnlKjph48nLAogICAgICAgIGtleXdvcmRzOiBbJ3VzYWdlJywgJ3Rva2Vu"
        "JywgJ+eUqOmHjyddLAogICAgICAgIHJ1bjogKCkgPT4geyBoYXB0aWMoJ3RhcCcpOyBob3N0Lm5h"
        "dmlnYXRlKCcvdXNhZ2UnKSB9CiAgICAgIH0KICAgIH0pCiAgfQp9Cg=="
    )

B64_plugins_hermes_usage_dashboard_plugin_api_py = (
        "IiIiSGVybWVzIFVzYWdlIOKAlCBwZXJzaXN0ZW50IHRva2VuLXVzYWdlIGJhY2tlbmQgKHJlYWRz"
        "IEhlcm1lcycgb3duIHN0YXRlLmRiKS4KCkEgRmFzdEFQSSByb3V0ZXIgbW91bnRlZCBhdCAvYXBp"
        "L3BsdWdpbnMvaGVybWVzLXVzYWdlLyogYnkgdGhlIGRhc2hib2FyZC9kZXNrdG9wCnBsdWdpbiBz"
        "eXN0ZW0uIEl0IGlzIHRoZSBzZXJ2ZXItc2lkZSBoYWxmIG9mIGEgImRzaC10b2tlbi11c2FnZSIt"
        "c3R5bGUgbG9jYWwKb2JzZXJ2YWJpbGl0eSB0b29sOiBpdCByZWFkcyB0aGUgU0FNRSB1c2FnZSBk"
        "YXRhIEhlcm1lcyBhbHJlYWR5IHBlcnNpc3RzIGluCnN0YXRlLmRiIChzZXNzaW9ucyArIHNlc3Np"
        "b25fbW9kZWxfdXNhZ2UpIGFuZCByZXR1cm5zIGRzaC1zdHlsZSBhZ2dyZWdhdGlvbnMg4oCUCnRv"
        "dGFscywgcGVyIHByb3ZpZGVyL21vZGVsLCBwZXIgc2Vzc2lvbiwgZGFpbHkgdHJlbmQsIGNhY2hl"
        "IHN0cnVjdHVyZSBhbmQKZXN0aW1hdGVkIGNvc3QuIEl0IG5ldmVyIHdyaXRlcyB0byB0aGUgREIg"
        "YW5kIG5ldmVyIHRvdWNoZXMgbW9kZWwgaGlzdG9yeS4KCkVudiBvdmVycmlkZSBmb3IgdGVzdGlu"
        "ZyBvbmx5OiBzZXQgSEVSTUVTX1VTQUdFX0RCIHRvIGEgc3RhdGUuZGIgcGF0aAooZS5nLiBhIGJh"
        "Y2t1cCBzbmFwc2hvdCkgdG8gcG9pbnQgdGhlIHF1ZXJpZXMgYXQgYSBjb3B5LgoiIiIKCmZyb20g"
        "X19mdXR1cmVfXyBpbXBvcnQgYW5ub3RhdGlvbnMKCmltcG9ydCBvcwppbXBvcnQgc3FsaXRlMwpp"
        "bXBvcnQgdGltZQpmcm9tIGRhdGV0aW1lIGltcG9ydCBkYXRldGltZSwgdGltZXpvbmUKZnJvbSBw"
        "YXRobGliIGltcG9ydCBQYXRoCgpmcm9tIGZhc3RhcGkgaW1wb3J0IEFQSVJvdXRlcgoKcm91dGVy"
        "ID0gQVBJUm91dGVyKCkKCiMgTWFwIG9mIFVUQyBkYXRlIHJhbmdlcyBvdmVyIHdoaWNoIGNhY2hl"
        "X3JlYWQvY2FjaGVfd3JpdGUgYXJlIGF1dGhvcml0YXRpdmUuCiMgQ2FjaGUgZmllbGRzIGFyZSBv"
        "bmx5IHN1bW1lZCB3aGVuIHRoZSBzb3VyY2Ugcm93IHBvcHVsYXRlZCB0aGVtIChzZWUgcXVlcmll"
        "cykuCgpfVVRDX0RBWSA9IDg2NDAwLjAKCgpkZWYgX3Jlc29sdmVfZGJfcGF0aCgpIC0+IFBhdGg6"
        "CiAgICBvdmVycmlkZSA9IG9zLmVudmlyb24uZ2V0KCJIRVJNRVNfVVNBR0VfREIiKQogICAgaWYg"
        "b3ZlcnJpZGU6CiAgICAgICAgcmV0dXJuIFBhdGgob3ZlcnJpZGUpCiAgICBob21lID0gb3MuZW52"
        "aXJvbi5nZXQoIkhFUk1FU19IT01FIikKICAgIGlmIG5vdCBob21lOgogICAgICAgIHRyeToKICAg"
        "ICAgICAgICAgZnJvbSBoZXJtZXNfY29uc3RhbnRzIGltcG9ydCBnZXRfcHJvY2Vzc19oZXJtZXNf"
        "aG9tZQoKICAgICAgICAgICAgaG9tZSA9IHN0cihnZXRfcHJvY2Vzc19oZXJtZXNfaG9tZSgpKQog"
        "ICAgICAgIGV4Y2VwdCBFeGNlcHRpb246CiAgICAgICAgICAgIGhvbWUgPSBOb25lCiAgICBpZiBu"
        "b3QgaG9tZToKICAgICAgICBob21lID0gc3RyKFBhdGguaG9tZSgpIC8gIi5oZXJtZXMiKQogICAg"
        "cmV0dXJuIFBhdGgoaG9tZSkgLyAic3RhdGUuZGIiCgoKZGVmIF9jb25uZWN0KGRiX3BhdGg6IFBh"
        "dGgpIC0+IHNxbGl0ZTMuQ29ubmVjdGlvbjoKICAgICIiIlJlYWQtb25seSBjb25uZWN0aW9uOyBk"
        "ZWdyYWRlcyB0byBpbW11dGFibGUgKG5vIFdBTCkgb24gbG9jayBlcnJvcnMuIiIiCiAgICB1cmkg"
        "PSBmImZpbGU6e2RiX3BhdGguYXNfcG9zaXgoKX0/bW9kZT1ybyIKICAgIHRyeToKICAgICAgICBy"
        "ZXR1cm4gc3FsaXRlMy5jb25uZWN0KHVyaSwgdXJpPVRydWUsIHRpbWVvdXQ9NSkKICAgIGV4Y2Vw"
        "dCBzcWxpdGUzLkVycm9yOgogICAgICAgIHBhc3MKICAgIHRyeToKICAgICAgICByZXR1cm4gc3Fs"
        "aXRlMy5jb25uZWN0KHVyaSArICImaW1tdXRhYmxlPTEiLCB1cmk9VHJ1ZSwgdGltZW91dD01KQog"
        "ICAgZXhjZXB0IHNxbGl0ZTMuRXJyb3I6CiAgICAgICAgIyBMYXN0IHJlc29ydDogbm9ybWFsIHJl"
        "YWQtd3JpdGUgb3BlbiAoc2FmZSBmb3IgU0VMRUNUcyBpbiBXQUwgbW9kZSkuCiAgICAgICAgcmV0"
        "dXJuIHNxbGl0ZTMuY29ubmVjdChzdHIoZGJfcGF0aCksIHRpbWVvdXQ9NSkKCgpkZWYgX2Yodik6"
        "CiAgICByZXR1cm4gTm9uZSBpZiB2IGlzIE5vbmUgZWxzZSBmbG9hdCh2KQoKCmRlZiBfbm93X3V0"
        "Y19kYXkoKSAtPiBpbnQ6CiAgICByZXR1cm4gaW50KHRpbWUudGltZSgpKSAvLyA4NjQwMAoKCkBy"
        "b3V0ZXIuZ2V0KCIvaGVhbHRoIikKYXN5bmMgZGVmIGhlYWx0aCgpOgogICAgcmV0dXJuIHsib2si"
        "OiBUcnVlLCAiZGIiOiBzdHIoX3Jlc29sdmVfZGJfcGF0aCgpKX0KCgpAcm91dGVyLmdldCgiL3Nl"
        "c3Npb25fbW9kZWxzIikKYXN5bmMgZGVmIHNlc3Npb25fbW9kZWxzKHNlc3Npb25faWQ6IHN0ciA9"
        "ICIiKToKICAgICIiIlBlci1tb2RlbCB1c2FnZSBicmVha2Rvd24gZm9yIG9uZSBzZXNzaW9uIChz"
        "ZXNzaW9uX2lkID0gZHVyYWJsZSBzZXNzaW9uIGlkKS4iIiIKICAgIGlmIG5vdCBzZXNzaW9uX2lk"
        "OgogICAgICAgIHJldHVybiB7Im9rIjogRmFsc2UsICJlcnJvciI6ICJtaXNzaW5nIHNlc3Npb25f"
        "aWQgcXVlcnkgcGFyYW0ifQogICAgZGIgPSBfcmVzb2x2ZV9kYl9wYXRoKCkKICAgIGlmIG5vdCBk"
        "Yi5leGlzdHMoKToKICAgICAgICByZXR1cm4geyJvayI6IEZhbHNlLCAiZXJyb3IiOiBmInN0YXRl"
        "LmRiIG5vdCBmb3VuZCBhdCB7ZGJ9In0KICAgIGNvbm4gPSBfY29ubmVjdChkYikKICAgIGNvbm4u"
        "cm93X2ZhY3RvcnkgPSBzcWxpdGUzLlJvdwogICAgdHJ5OgogICAgICAgIHJvd3MgPSBbCiAgICAg"
        "ICAgICAgIGRpY3QocikKICAgICAgICAgICAgZm9yIHIgaW4gY29ubi5leGVjdXRlKAogICAgICAg"
        "ICAgICAgICAgInNlbGVjdCBiaWxsaW5nX3Byb3ZpZGVyIGFzIHByb3ZpZGVyLCBtb2RlbCwgIgog"
        "ICAgICAgICAgICAgICAgInN1bShhcGlfY2FsbF9jb3VudCkgYXMgY2FsbHMsICIKICAgICAgICAg"
        "ICAgICAgICJzdW0oaW5wdXRfdG9rZW5zKSBhcyBpbnB1dCwgc3VtKG91dHB1dF90b2tlbnMpIGFz"
        "IG91dHB1dCwgIgogICAgICAgICAgICAgICAgInN1bShjYWNoZV9yZWFkX3Rva2VucykgYXMgY2Fj"
        "aGVfcmVhZCwgc3VtKGNhY2hlX3dyaXRlX3Rva2VucykgYXMgY2FjaGVfd3JpdGUsICIKICAgICAg"
        "ICAgICAgICAgICJzdW0ocmVhc29uaW5nX3Rva2VucykgYXMgcmVhc29uaW5nLCAiCiAgICAgICAg"
        "ICAgICAgICAicm91bmQoc3VtKGNvYWxlc2NlKGVzdGltYXRlZF9jb3N0X3VzZCwgYWN0dWFsX2Nv"
        "c3RfdXNkLCAwKSksIDYpIGFzIGVzdF91c2QgIgogICAgICAgICAgICAgICAgImZyb20gc2Vzc2lv"
        "bl9tb2RlbF91c2FnZSB3aGVyZSBzZXNzaW9uX2lkID0gPyAiCiAgICAgICAgICAgICAgICAiZ3Jv"
        "dXAgYnkgYmlsbGluZ19wcm92aWRlciwgbW9kZWwgIgogICAgICAgICAgICAgICAgIm9yZGVyIGJ5"
        "IChzdW0oaW5wdXRfdG9rZW5zKStzdW0ob3V0cHV0X3Rva2Vucykrc3VtKGNhY2hlX3JlYWRfdG9r"
        "ZW5zKStzdW0oY2FjaGVfd3JpdGVfdG9rZW5zKSkgZGVzYyIsCiAgICAgICAgICAgICAgICAoc2Vz"
        "c2lvbl9pZCwpLAogICAgICAgICAgICApLmZldGNoYWxsKCkKICAgICAgICBdCiAgICAgICAgZm9y"
        "IHJvdyBpbiByb3dzOgogICAgICAgICAgICB0ID0gKHJvdy5nZXQoImlucHV0Iikgb3IgMCkgKyAo"
        "cm93LmdldCgib3V0cHV0Iikgb3IgMCkKICAgICAgICAgICAgY3IgPSByb3cuZ2V0KCJjYWNoZV9y"
        "ZWFkIikgb3IgMAogICAgICAgICAgICByb3dbInRvdGFsIl0gPSB0ICsgY3IgKyAocm93LmdldCgi"
        "Y2FjaGVfd3JpdGUiKSBvciAwKQogICAgICAgICAgICBpZiByb3cuZ2V0KCJlc3RfdXNkIikgaXMg"
        "bm90IE5vbmU6CiAgICAgICAgICAgICAgICByb3dbImVzdF91c2QiXSA9IHJvdW5kKHJvd1siZXN0"
        "X3VzZCJdLCA2KQogICAgICAgIHJldHVybiB7Im9rIjogVHJ1ZSwgInNlc3Npb25faWQiOiBzZXNz"
        "aW9uX2lkLCAibW9kZWxzIjogcm93c30KICAgIGZpbmFsbHk6CiAgICAgICAgY29ubi5jbG9zZSgp"
        "CgoKQHJvdXRlci5nZXQoIi9vdmVydmlldyIpCmFzeW5jIGRlZiBvdmVydmlldygpOgogICAgZGIg"
        "PSBfcmVzb2x2ZV9kYl9wYXRoKCkKICAgIGlmIG5vdCBkYi5leGlzdHMoKToKICAgICAgICByZXR1"
        "cm4gewogICAgICAgICAgICAib2siOiBGYWxzZSwKICAgICAgICAgICAgImVycm9yIjogZiJzdGF0"
        "ZS5kYiBub3QgZm91bmQgYXQge2RifSIsCiAgICAgICAgICAgICJtZXRhIjoge30sCiAgICAgICAg"
        "ICAgICJ0b3RhbHMiOiB7fSwKICAgICAgICAgICAgInBlcl9tb2RlbCI6IFtdLAogICAgICAgICAg"
        "ICAicGVyX3Nlc3Npb24iOiBbXSwKICAgICAgICAgICAgImRhaWx5IjogW10sCiAgICAgICAgfQog"
        "ICAgY29ubiA9IF9jb25uZWN0KGRiKQogICAgY29ubi5yb3dfZmFjdG9yeSA9IHNxbGl0ZTMuUm93"
        "CiAgICB0cnk6CiAgICAgICAgbWV0YSA9IGRpY3QoY29ubi5leGVjdXRlKAogICAgICAgICAgICAi"
        "c2VsZWN0IGNvdW50KCopIGFzIGFwaV9jYWxscywgY291bnQoZGlzdGluY3Qgc2Vzc2lvbl9pZCkg"
        "YXMgc2Vzc2lvbnMsICIKICAgICAgICAgICAgImNvdW50KGRpc3RpbmN0IG1vZGVsKSBhcyBtb2Rl"
        "bHMsICIKICAgICAgICAgICAgIm1pbihmaXJzdF9zZWVuKSBhcyBmaXJzdF9zZWVuLCBtYXgobGFz"
        "dF9zZWVuKSBhcyBsYXN0X3NlZW4gIgogICAgICAgICAgICAiZnJvbSBzZXNzaW9uX21vZGVsX3Vz"
        "YWdlIgogICAgICAgICkuZmV0Y2hvbmUoKSkKCiAgICAgICAgdG90YWxzID0gZGljdChjb25uLmV4"
        "ZWN1dGUoCiAgICAgICAgICAgICJzZWxlY3QgY29hbGVzY2Uoc3VtKGlucHV0X3Rva2VucyksMCkg"
        "YXMgaW5wdXQsICIKICAgICAgICAgICAgImNvYWxlc2NlKHN1bShvdXRwdXRfdG9rZW5zKSwwKSBh"
        "cyBvdXRwdXQsICIKICAgICAgICAgICAgImNvYWxlc2NlKHN1bShjYWNoZV9yZWFkX3Rva2Vucyks"
        "MCkgYXMgY2FjaGVfcmVhZCwgIgogICAgICAgICAgICAiY29hbGVzY2Uoc3VtKGNhY2hlX3dyaXRl"
        "X3Rva2VucyksMCkgYXMgY2FjaGVfd3JpdGUsICIKICAgICAgICAgICAgImNvYWxlc2NlKHN1bShy"
        "ZWFzb25pbmdfdG9rZW5zKSwwKSBhcyByZWFzb25pbmcsICIKICAgICAgICAgICAgImNvYWxlc2Nl"
        "KHN1bShhcGlfY2FsbF9jb3VudCksMCkgYXMgYXBpX2NhbGxzICIKICAgICAgICAgICAgImZyb20g"
        "c2Vzc2lvbl9tb2RlbF91c2FnZSIKICAgICAgICApLmZldGNob25lKCkpCgogICAgICAgICMgRXN0"
        "aW1hdGVkIGNvc3QgYWNyb3NzIHRoZSB3aG9sZSB0YWJsZSAoZXN0aW1hdGVkIHdoZXJlIHByZXNl"
        "bnQsIGVsc2UgYWN0dWFsKS4KICAgICAgICBjb3N0ID0gY29ubi5leGVjdXRlKAogICAgICAgICAg"
        "ICAic2VsZWN0IGNvYWxlc2NlKHN1bShjb2FsZXNjZShlc3RpbWF0ZWRfY29zdF91c2QsIGFjdHVh"
        "bF9jb3N0X3VzZCwgMCkpLDApIGFzIGVzdF91c2QsICIKICAgICAgICAgICAgImNvdW50KCopIGZp"
        "bHRlciAod2hlcmUgZXN0aW1hdGVkX2Nvc3RfdXNkIGlzIG5vdCBudWxsIGFuZCBlc3RpbWF0ZWRf"
        "Y29zdF91c2QgPiAwKSBhcyBlc3Rfcm93cywgIgogICAgICAgICAgICAiY291bnQoKikgZmlsdGVy"
        "ICh3aGVyZSBhY3R1YWxfY29zdF91c2QgaXMgbm90IG51bGwgYW5kIGFjdHVhbF9jb3N0X3VzZCA+"
        "IDApIGFzIGFjdF9yb3dzICIKICAgICAgICAgICAgImZyb20gc2Vzc2lvbl9tb2RlbF91c2FnZSIK"
        "ICAgICAgICApLmZldGNob25lKCkKICAgICAgICBtZXRhWyJlc3Rfcm93cyJdID0gY29zdFsiZXN0"
        "X3Jvd3MiXQogICAgICAgIG1ldGFbImFjdF9yb3dzIl0gPSBjb3N0WyJhY3Rfcm93cyJdCiAgICAg"
        "ICAgbWV0YVsiZXN0X3VzZCJdID0gcm91bmQoX2YoY29zdFsiZXN0X3VzZCJdKSBvciAwLjAsIDYp"
        "CgogICAgICAgIHRpbiA9IHRvdGFsc1siaW5wdXQiXSBvciAwCiAgICAgICAgY2FjaGVfcmVhZCA9"
        "IHRvdGFsc1siY2FjaGVfcmVhZCJdIG9yIDAKICAgICAgICB0b3RhbHNbInRvdGFsIl0gPSB0aW4g"
        "KyAodG90YWxzWyJvdXRwdXQiXSBvciAwKSArIGNhY2hlX3JlYWQgKyAodG90YWxzWyJjYWNoZV93"
        "cml0ZSJdIG9yIDApCiAgICAgICAgdG90YWxzWyJjYWNoZV9zaGFyZV9vZl9pbnB1dCJdID0gcm91"
        "bmQoY2FjaGVfcmVhZCAvIHRpbiwgNCkgaWYgdGluIGVsc2UgTm9uZQogICAgICAgIHRvdGFsc1si"
        "ZXN0X3VzZCJdID0gbWV0YVsiZXN0X3VzZCJdCgogICAgICAgIHBlcl9tb2RlbCA9IFsKICAgICAg"
        "ICAgICAgZGljdChyKQogICAgICAgICAgICBmb3IgciBpbiBjb25uLmV4ZWN1dGUoCiAgICAgICAg"
        "ICAgICAgICAic2VsZWN0IGJpbGxpbmdfcHJvdmlkZXIgYXMgcHJvdmlkZXIsIG1vZGVsLCBjb3Vu"
        "dCgqKSBhcyBjYWxscywgIgogICAgICAgICAgICAgICAgInN1bShpbnB1dF90b2tlbnMpIGFzIGlu"
        "cHV0LCBzdW0ob3V0cHV0X3Rva2VucykgYXMgb3V0cHV0LCAiCiAgICAgICAgICAgICAgICAic3Vt"
        "KGNhY2hlX3JlYWRfdG9rZW5zKSBhcyBjYWNoZV9yZWFkLCBzdW0oY2FjaGVfd3JpdGVfdG9rZW5z"
        "KSBhcyBjYWNoZV93cml0ZSwgIgogICAgICAgICAgICAgICAgInN1bShyZWFzb25pbmdfdG9rZW5z"
        "KSBhcyByZWFzb25pbmcsICIKICAgICAgICAgICAgICAgICJyb3VuZChzdW0oY29hbGVzY2UoZXN0"
        "aW1hdGVkX2Nvc3RfdXNkLCBhY3R1YWxfY29zdF91c2QsIDApKSwgNikgYXMgZXN0X3VzZCAiCiAg"
        "ICAgICAgICAgICAgICAiZnJvbSBzZXNzaW9uX21vZGVsX3VzYWdlIGdyb3VwIGJ5IGJpbGxpbmdf"
        "cHJvdmlkZXIsIG1vZGVsICIKICAgICAgICAgICAgICAgICJvcmRlciBieSAoc3VtKGlucHV0X3Rv"
        "a2Vucykrc3VtKG91dHB1dF90b2tlbnMpK3N1bShjYWNoZV9yZWFkX3Rva2Vucykrc3VtKGNhY2hl"
        "X3dyaXRlX3Rva2VucykpIGRlc2MiCiAgICAgICAgICAgICkuZmV0Y2hhbGwoKQogICAgICAgIF0K"
        "ICAgICAgICBmb3Igcm93IGluIHBlcl9tb2RlbDoKICAgICAgICAgICAgdCA9IChyb3cuZ2V0KCJp"
        "bnB1dCIpIG9yIDApICsgKHJvdy5nZXQoIm91dHB1dCIpIG9yIDApCiAgICAgICAgICAgIGNyID0g"
        "cm93LmdldCgiY2FjaGVfcmVhZCIpIG9yIDAKICAgICAgICAgICAgcm93WyJ0b3RhbCJdID0gdCAr"
        "IGNyICsgKHJvdy5nZXQoImNhY2hlX3dyaXRlIikgb3IgMCkKICAgICAgICAgICAgcm93WyJjYWNo"
        "ZV9zaGFyZV9vZl9pbnB1dCJdID0gcm91bmQoY3IgLyAocm93LmdldCgiaW5wdXQiKSBvciAwKSwg"
        "NCkgaWYgcm93LmdldCgiaW5wdXQiKSBlbHNlIE5vbmUKICAgICAgICAgICAgaWYgcm93LmdldCgi"
        "ZXN0X3VzZCIpIGlzIG5vdCBOb25lOgogICAgICAgICAgICAgICAgcm93WyJlc3RfdXNkIl0gPSBy"
        "b3VuZChyb3dbImVzdF91c2QiXSwgNikKCiAgICAgICAgcGVyX3Nlc3Npb24gPSBbCiAgICAgICAg"
        "ICAgIGRpY3QocikKICAgICAgICAgICAgZm9yIHIgaW4gY29ubi5leGVjdXRlKAogICAgICAgICAg"
        "ICAgICAgInNlbGVjdCB1LnNlc3Npb25faWQsIGNvYWxlc2NlKHMudGl0bGUsIHMuZGlzcGxheV9u"
        "YW1lLCBzdWJzdHIocy5zZXNzaW9uX2tleSwxLDYwKSwgdS5zZXNzaW9uX2lkKSBhcyB0aXRsZSwg"
        "IgogICAgICAgICAgICAgICAgInMuc3RhcnRlZF9hdCwgcy5sYXN0X2FjdGl2aXR5X2F0LCB1Lm1v"
        "ZGVsLCB1LmJpbGxpbmdfcHJvdmlkZXIgYXMgcHJvdmlkZXIsICIKICAgICAgICAgICAgICAgICJz"
        "dW0odS5pbnB1dF90b2tlbnMpIGFzIGlucHV0LCBzdW0odS5vdXRwdXRfdG9rZW5zKSBhcyBvdXRw"
        "dXQsICIKICAgICAgICAgICAgICAgICJzdW0odS5jYWNoZV9yZWFkX3Rva2VucykgYXMgY2FjaGVf"
        "cmVhZCwgc3VtKHUuY2FjaGVfd3JpdGVfdG9rZW5zKSBhcyBjYWNoZV93cml0ZSwgIgogICAgICAg"
        "ICAgICAgICAgInN1bSh1LnJlYXNvbmluZ190b2tlbnMpIGFzIHJlYXNvbmluZywgc3VtKHUuYXBp"
        "X2NhbGxfY291bnQpIGFzIGNhbGxzLCAiCiAgICAgICAgICAgICAgICAicm91bmQoc3VtKGNvYWxl"
        "c2NlKHUuZXN0aW1hdGVkX2Nvc3RfdXNkLCB1LmFjdHVhbF9jb3N0X3VzZCwgMCkpLCA2KSBhcyBl"
        "c3RfdXNkICIKICAgICAgICAgICAgICAgICJmcm9tIHNlc3Npb25fbW9kZWxfdXNhZ2UgdSBsZWZ0"
        "IGpvaW4gc2Vzc2lvbnMgcyBvbiBzLmlkID0gdS5zZXNzaW9uX2lkICIKICAgICAgICAgICAgICAg"
        "ICJncm91cCBieSB1LnNlc3Npb25faWQgb3JkZXIgYnkgKHN1bSh1LmlucHV0X3Rva2Vucykrc3Vt"
        "KHUub3V0cHV0X3Rva2VucykrIgogICAgICAgICAgICAgICAgInN1bSh1LmNhY2hlX3JlYWRfdG9r"
        "ZW5zKStzdW0odS5jYWNoZV93cml0ZV90b2tlbnMpKSBkZXNjIGxpbWl0IDMwIgogICAgICAgICAg"
        "ICApLmZldGNoYWxsKCkKICAgICAgICBdCiAgICAgICAgZm9yIHJvdyBpbiBwZXJfc2Vzc2lvbjoK"
        "ICAgICAgICAgICAgdCA9IChyb3cuZ2V0KCJpbnB1dCIpIG9yIDApICsgKHJvdy5nZXQoIm91dHB1"
        "dCIpIG9yIDApCiAgICAgICAgICAgIGNyID0gcm93LmdldCgiY2FjaGVfcmVhZCIpIG9yIDAKICAg"
        "ICAgICAgICAgcm93WyJ0b3RhbCJdID0gdCArIGNyICsgKHJvdy5nZXQoImNhY2hlX3dyaXRlIikg"
        "b3IgMCkKCiAgICAgICAgIyBEYWlseSB0cmVuZCBvdmVyIHRoZSBsYXN0IE4gY29tcGxldGUtaXNo"
        "IFVUQyBkYXlzLCBidWNrZXRlZCBieSBmaXJzdF9zZWVuLgogICAgICAgIG5fZGF5cyA9IDMwCiAg"
        "ICAgICAgc3RhcnQgPSBfbm93X3V0Y19kYXkoKSAtIChuX2RheXMgLSAxKQogICAgICAgIHJvd3Mg"
        "PSBjb25uLmV4ZWN1dGUoCiAgICAgICAgICAgICJzZWxlY3QgY2FzdChmaXJzdF9zZWVuIC8gODY0"
        "MDAuMCBhcyBpbnQpIGFzIGRheSwgIgogICAgICAgICAgICAic3VtKGlucHV0X3Rva2VucykgYXMg"
        "aW5wdXQsIHN1bShvdXRwdXRfdG9rZW5zKSBhcyBvdXRwdXQsICIKICAgICAgICAgICAgInN1bShj"
        "YWNoZV9yZWFkX3Rva2VucykgYXMgY2FjaGVfcmVhZCwgc3VtKGNhY2hlX3dyaXRlX3Rva2Vucykg"
        "YXMgY2FjaGVfd3JpdGUsICIKICAgICAgICAgICAgInN1bShyZWFzb25pbmdfdG9rZW5zKSBhcyBy"
        "ZWFzb25pbmcsICIKICAgICAgICAgICAgInJvdW5kKHN1bShjb2FsZXNjZShlc3RpbWF0ZWRfY29z"
        "dF91c2QsIGFjdHVhbF9jb3N0X3VzZCwgMCkpLCA2KSBhcyBlc3RfdXNkICIKICAgICAgICAgICAg"
        "ImZyb20gc2Vzc2lvbl9tb2RlbF91c2FnZSBncm91cCBieSBkYXkiCiAgICAgICAgKS5mZXRjaGFs"
        "bCgpCiAgICAgICAgYnlfZGF5ID0ge3JbImRheSJdOiByIGZvciByIGluIHJvd3N9CiAgICAgICAg"
        "ZGFpbHkgPSBbXQogICAgICAgIGZvciBkIGluIHJhbmdlKHN0YXJ0LCBzdGFydCArIG5fZGF5cyk6"
        "CiAgICAgICAgICAgIHIgPSBieV9kYXkuZ2V0KGQpCiAgICAgICAgICAgIGRheV9kYXRlID0gZGF0"
        "ZXRpbWUuZnJvbXRpbWVzdGFtcChkICogX1VUQ19EQVksIHR6PXRpbWV6b25lLnV0Yykuc3RyZnRp"
        "bWUoIiVZLSVtLSVkIikKICAgICAgICAgICAgaWYgciBpcyBOb25lOgogICAgICAgICAgICAgICAg"
        "ZGFpbHkuYXBwZW5kKHsiZGF0ZSI6IGRheV9kYXRlLCAiZGF5IjogZCwgImFjdGl2ZSI6IEZhbHNl"
        "fSkKICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgIHRvdGFsID0gKHJbImlucHV0"
        "Il0gb3IgMCkgKyAoclsib3V0cHV0Il0gb3IgMCkgKyAoclsiY2FjaGVfcmVhZCJdIG9yIDApICsg"
        "KHJbImNhY2hlX3dyaXRlIl0gb3IgMCkKICAgICAgICAgICAgZGFpbHkuYXBwZW5kKHsKICAgICAg"
        "ICAgICAgICAgICJkYXRlIjogZGF5X2RhdGUsICJkYXkiOiBkLCAiYWN0aXZlIjogVHJ1ZSwgInRv"
        "dGFsIjogdG90YWwsCiAgICAgICAgICAgICAgICAiaW5wdXQiOiByWyJpbnB1dCJdIG9yIDAsICJv"
        "dXRwdXQiOiByWyJvdXRwdXQiXSBvciAwLAogICAgICAgICAgICAgICAgImNhY2hlX3JlYWQiOiBy"
        "WyJjYWNoZV9yZWFkIl0gb3IgMCwgImNhY2hlX3dyaXRlIjogclsiY2FjaGVfd3JpdGUiXSBvciAw"
        "LAogICAgICAgICAgICAgICAgInJlYXNvbmluZyI6IHJbInJlYXNvbmluZyJdIG9yIDAsCiAgICAg"
        "ICAgICAgICAgICAiZXN0X3VzZCI6IHJvdW5kKHJbImVzdF91c2QiXSBvciAwLCA2KSBpZiByWyJl"
        "c3RfdXNkIl0gaXMgbm90IE5vbmUgZWxzZSBOb25lLAogICAgICAgICAgICB9KQoKICAgICAgICBy"
        "ZXR1cm4gewogICAgICAgICAgICAib2siOiBUcnVlLAogICAgICAgICAgICAibWV0YSI6IG1ldGEs"
        "CiAgICAgICAgICAgICJ0b3RhbHMiOiB0b3RhbHMsCiAgICAgICAgICAgICJwZXJfbW9kZWwiOiBw"
        "ZXJfbW9kZWwsCiAgICAgICAgICAgICJwZXJfc2Vzc2lvbiI6IHBlcl9zZXNzaW9uLAogICAgICAg"
        "ICAgICAiZGFpbHkiOiBkYWlseSwKICAgICAgICB9CiAgICBmaW5hbGx5OgogICAgICAgIGNvbm4u"
        "Y2xvc2UoKQo="
    )

B64_plugins_hermes_usage_dashboard_manifest_json = (
        "ewogICJuYW1lIjogImhlcm1lcy11c2FnZSIsCiAgImxhYmVsIjogIlRva2VuIOeUqOmHjyIsCiAg"
        "ImRlc2NyaXB0aW9uIjogIlBlcnNpc3RlbnQgdG9rZW4tdXNhZ2UgYmFja2VuZDogcmVhZHMgSGVy"
        "bWVzJyBvd24gc3RhdGUuZGIgKHNlc3Npb25zICsgc2Vzc2lvbl9tb2RlbF91c2FnZSkgYW5kIHNl"
        "cnZlcyBkc2gtdG9rZW4tdXNhZ2Utc3R5bGUgYWdncmVnYXRpb25zIHRvIHRoZSBkZXNrdG9wIC91"
        "c2FnZSBkYXNoYm9hcmQuIEJhY2tlbmQgb25seSDigJQgbm8gd2ViLWRhc2hib2FyZCB0YWIuIiwK"
        "ICAiaWNvbiI6ICJHcmFwaExpbmUiLAogICJ2ZXJzaW9uIjogIjAuMS4wIiwKICAiYXBpIjogInBs"
        "dWdpbl9hcGkucHkiCn0K"
    )

def candidate_homes():
    out = []
    env = os.environ.get("HERMES_HOME")
    if env:
        out.append(Path(env))
    out.append(Path.home() / ".hermes")
    la = os.environ.get("LOCALAPPDATA")
    if la:
        out.append(Path(la) / "hermes")
    dedup = []
    for h in out:
        if h not in dedup:
            dedup.append(h)
    return dedup

def detect(homes):
    env = os.environ.get("HERMES_HOME")
    if env:
        return Path(env)
    scored = []
    for h in homes:
        if not h.exists():
            continue
        s = 0
        if (h / "config.yaml").exists():
            s += 2
        if (h / "state.db").exists():
            s += 4
        if (h / "desktop-plugins").is_dir():
            s += 4
        if (h / "plugins").is_dir():
            s += 2
        if (h / "desktop-plugins" / "hermes-usage").is_dir():
            s += 9
        scored.append((s, h))
    if not scored:
        return (homes[0] if homes else Path.home() / ".hermes")
    scored.sort(key=lambda x: x[0], reverse=True)
    return scored[0][1]

ARTIFACTS = [
    ("desktop-plugins/hermes-usage/plugin.js", B64_desktop_plugins_hermes_usage_plugin_js),
    ("plugins/hermes-usage/dashboard/plugin_api.py", B64_plugins_hermes_usage_dashboard_plugin_api_py),
    ("plugins/hermes-usage/dashboard/manifest.json", B64_plugins_hermes_usage_dashboard_manifest_json),
]

def write_files(home, bar_only):
    n = 0
    for rel, b64 in ARTIFACTS:
        if bar_only and not rel.startswith("desktop-plugins"):
            continue
        p = home / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(base64.b64decode(b64))
        print("  wrote  %s" % rel)
        n += 1
    return n

def enable_backend(home):
    cfg = home / "config.yaml"
    if not cfg.exists():
        print("  !! 未找到 config.yaml, 跳过后端启用(底部条仍可用; 详情页需要后端)")
        print("     手动启用: hermes config set plugins.enabled \"['hermes-usage']\"")
        return
    try:
        import yaml
    except Exception:
        print("  !! 本机无 PyYAML, 跳过自动启用(不影响底部条)")
        print("     手动启用: hermes config set plugins.enabled \"['hermes-usage']\"")
        return
    try:
        data = yaml.safe_load(cfg.read_text(encoding="utf-8")) or {}
    except Exception as ex:
        print("  !! 读取 config.yaml 失败 (%s), 跳过自动启用" % ex)
        return
    plugins = data.get("plugins")
    if not isinstance(plugins, dict):
        plugins = {}
        data["plugins"] = plugins
    enabled = plugins.get("enabled")
    if not isinstance(enabled, list):
        enabled = []
    if "hermes-usage" not in enabled:
        enabled.append("hermes-usage")
    plugins["enabled"] = enabled
    bak = cfg.with_name(cfg.name + ".bak-hermes-usage")
    if not bak.exists():
        try:
            bak.write_text(cfg.read_text(encoding="utf-8"), encoding="utf-8")
        except Exception:
            pass
    try:
        cfg.write_text(
            yaml.safe_dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False),
            encoding="utf-8",
        )
        print("  已将 'hermes-usage' 加入 plugins.enabled (原配置已备份为 config.yaml.bak-hermes-usage)")
    except Exception as ex:
        print("  !! 写回 config.yaml 失败 (%s)" % ex)
        print("     手动启用: hermes config set plugins.enabled \"['hermes-usage']\"")

def _read_serve_port(home):
    """Find the port of the desktop backend. Hermes service (serve) logs
    `HERMES_BACKEND_READY port=N` into <home>/logs/desktop.log on boot."""
    log = home / "logs" / "desktop.log"
    if not log.exists():
        return None
    try:
        txt = log.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return None
    import re as _re
    ports = _re.findall(r"HERMES_BACKEND_READY port=(\d+)", txt)
    return ports[-1] if ports else None


def verify_backend(home):
    """Best-effort online check: is /api/plugins/hermes-usage/ live yet?

    Hermes mounts a plugin's API route only at serve-startup AND only if the
    plugin was in plugins.enabled at that moment. If a desktop app was already
    running when this plugin was enabled, the route is missing until the app is
    FULLY restarted (tray quit -> reopen). This probe tells the user which case
    they are in. Never raises; prints for humans.
    """
    try:
        import json  # noqa: F401
        import re as _re
        import urllib.error
        import urllib.request
    except Exception:
        return
    port = _read_serve_port(home)
    if not port:
        print("  ? 无法读取桌面后端端口(desktop.log), 跳过在线自检")
        return
    base = "http://127.0.0.1:%s" % port
    try:
        with urllib.request.urlopen(base + "/", timeout=5) as r:
            html = r.read().decode("utf-8", "ignore")
    except Exception as ex:
        print("  ? 无法连接桌面后端 (%s:%s): %s" % (base, "", ex))
        return
    m = _re.search(r'__HERMES_SESSION_TOKEN__="([^"]+)"', html)
    token = m.group(1) if m else ""
    if not token:
        print("  ? 未取得会话 token, 跳过在线自检")
        return
    url = base + "/api/plugins/hermes-usage/overview"
    req = urllib.request.Request(url, headers={"X-Hermes-Session-Token": token})
    try:
        with urllib.request.urlopen(req, timeout=5) as r:
            print("  ✓ 后端已挂载: %s -> HTTP %s (历史详情页可用)" % (url, r.status))
            return
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", "ignore")[:140]
        if e.code == 401:
            print("  ✓ 路由已就绪(401=鉴权通过后可用); 若 /usage 仍报错说明页面刚需刷新")
            print("    请在桌面端 Ctrl+K -> Reload desktop plugins 或重开应用后刷新 /usage")
        elif e.code == 404:
            print("  ✗ /usage 后端尚未挂载 (404)。原因: 桌面端 serve 是在启用插件前启动的。")
            print("    请【彻底退出桌面端(含托盘图标)】再重新打开, 然后刷新 /usage 页即可。")
            print("    (注意: 仅重启消息网关/hermes gateway 不解决此问题。)")
        else:
            print("  ? HTTP %s: %s (请退出并重开桌面端后刷新 /usage)" % (e.code, body))
    except Exception as ex:
        print("  ? 自检请求失败: %s" % ex)


def main():
    bar_only = "--bar-only" in sys.argv
    if "-h" in sys.argv or "--help" in sys.argv:
        print(__doc__)
        return 0
    homes = candidate_homes()
    home = detect(homes)
    print("Hermes 数据目录: %s" % home)
    if not home.exists():
        home.mkdir(parents=True, exist_ok=True)
    n = write_files(home, bar_only)
    print("  写入 %d 个文件" % n)
    if not bar_only:
        enable_backend(home)
    print()
    print("下一步（重要）。请完成以下操作，否则 /usage 历史详情页会一直报 404:")
    print("  1) 【彻底退出 Hermes 桌面端, 包括托盘图标】——从托盘右键选『退出/Quit』,")
    print("     而不是只关窗口。")
    print("  2) 重新打开桌面端。")
    print("  3) 打开 /usage 页(点底部用量条), 或按 Ctrl+K 输入 'Reload desktop plugins' 回车。")
    print()
    print("为什么必须这么做: Hermes 只在服务启动那一刻挂载插件后端路由, 且要求该插件已在")
    print("plugins.enabled 白名单里。若桌面端在启用插件前就已经在运行, 它不会重新挂载,")
    print("""除非把桌面端连同其后端(serve)整个重启。仅重启消息网关(hermes gateway)不解决此问题。""")
    print()
    print("正在尝试自检后端是否已挂载(需桌面端已运行)…")
    verify_backend(home)
    return 0

if __name__ == "__main__":
    sys.exit(main())
